import type { AbilityScores, Campaign, Character, CombatSession, MonsterInstance, MonsterTemplate, Scene, SceneOverlay, TabletopState, Token } from "./types";

const abilities: AbilityScores = { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 };
export const demoCampaign: Campaign = { id: "demo", name: "The Ember Archive", joinCode: "RUNE-72", ownerId: "demo-user", role: "OWNER", memberCount: 5, updatedAt: new Date().toISOString() };
export const demoScene: Scene = { id: "demo-scene", campaignId: "demo", mapId: null, name: "Ruined Library — Lower Hall", mapUrl: null, width: 1600, height: 1000, gridType: "SQUARE", gridSize: 80, feetPerCell: 5, gridColor: "#d9cab0", gridOpacity: .18, fogEnabled: true, fogCovered: false, active: true };
export const demoTemplate: MonsterTemplate = { id: "scout-template", campaignId: "demo", name: "Cave Scout", imageUrl: null, maxHp: 7, ac: 15, speed: 30, abilities, notes: "Keeps to cover and retreats when isolated.", traits: [{ name: "Nimble", description: "Can move through occupied spaces." }], actions: [{ name: "Rusty Shortsword", description: "A quick, close-range strike.", attackBonus: 4, damageExpression: "1d6 + 2", damageType: "piercing" }], bonusActions: [{ name: "Quick Retreat", description: "Move 15 feet without provoking reactions." }], reactions: [] };
export const demoCharacters: Character[] = [{ id: "char-1", campaignId: "demo", ownerId: "demo-user", name: "Elowen Vey", imageUrl: null, currentHp: 23, maxHp: 31, ac: 17, speed: 30, passivePerception: 15, passiveInvestigation: 13, passiveInsight: 12, notes: "Keeps the brass key from the upper stacks.", conditions: [] }, { id: "char-2", campaignId: "demo", ownerId: "player-2", name: "Kestrel", imageUrl: null, currentHp: 18, maxHp: 24, ac: 16, speed: 35, passivePerception: 14, passiveInvestigation: 11, passiveInsight: 13, notes: "", conditions: [] }];
export const demoMonsters: MonsterInstance[] = [{ id: "monster-1", campaignId: "demo", templateId: demoTemplate.id, customName: "Cave Scout A", currentHp: 5, maxHp: 7, ac: 15, conditions: ["Poisoned"], visible: true, notes: "Carries the archive key.", dead: false, template: demoTemplate }, { id: "monster-2", campaignId: "demo", templateId: demoTemplate.id, customName: "Cave Scout B", currentHp: 7, maxHp: 7, ac: 15, conditions: [], visible: true, notes: "", dead: false, template: demoTemplate }, { id: "monster-3", campaignId: "demo", templateId: demoTemplate.id, customName: "Hidden Scout", currentHp: 7, maxHp: 7, ac: 15, conditions: [], visible: false, notes: "Waiting behind the stacks.", dead: false, template: demoTemplate }];
export const demoTokens: Token[] = [{ id: "token-char-1", sceneId: demoScene.id, referenceId: "char-1", ownerUserId: "demo-user", type: "PLAYER", displayName: "Elowen", imageUrl: null, x: 560, y: 620, size: 1, rotation: 0, visible: true, locked: false, conditions: [] }, { id: "token-char-2", sceneId: demoScene.id, referenceId: "char-2", ownerUserId: "player-2", type: "PLAYER", displayName: "Kestrel", imageUrl: null, x: 700, y: 540, size: 1, rotation: 0, visible: true, locked: false, conditions: [] }, { id: "token-monster-1", sceneId: demoScene.id, referenceId: "monster-1", ownerUserId: null, type: "MONSTER", displayName: "Cave Scout A", imageUrl: null, x: 940, y: 410, size: 1, rotation: 0, visible: true, locked: false, conditions: ["Poisoned"] }, { id: "token-monster-2", sceneId: demoScene.id, referenceId: "monster-2", ownerUserId: null, type: "MONSTER", displayName: "Cave Scout B", imageUrl: null, x: 1100, y: 550, size: 1, rotation: 0, visible: true, locked: false, conditions: [] }, { id: "token-monster-3", sceneId: demoScene.id, referenceId: "monster-3", ownerUserId: null, type: "MONSTER", displayName: "Hidden Scout", imageUrl: null, x: 1210, y: 300, size: 1, rotation: 0, visible: false, locked: false, conditions: [] }];
export const demoOverlays: SceneOverlay[] = [{ id: "overlay-fire", sceneId: demoScene.id, name: "Smoldering floor", imageUrl: "", kind: "EFFECT", x: 830, y: 640, width: 220, height: 160, rotation: -.14, opacity: .82, zIndex: 4, visible: true, locked: false }];
export const demoCombat: CombatSession = { id: "combat-demo", campaignId: "demo", sceneId: demoScene.id, active: true, round: 2, currentIndex: 0, entries: [{ id: "init-1", combatSessionId: "combat-demo", tokenId: "token-char-1", monsterInstanceId: null, characterId: "char-1", name: "Elowen", imageUrl: null, initiative: 23, sortOrder: 0, groupKey: null, groupCount: 1 }, { id: "init-2", combatSessionId: "combat-demo", tokenId: null, monsterInstanceId: "monster-1", characterId: null, name: "Cave Scouts", imageUrl: null, initiative: 18, sortOrder: 1, groupKey: "scout-template", groupCount: 3 }, { id: "init-3", combatSessionId: "combat-demo", tokenId: "token-char-2", monsterInstanceId: null, characterId: "char-2", name: "Kestrel", imageUrl: null, initiative: 16, sortOrder: 2, groupKey: null, groupCount: 1 } ] };
export const createDemoState = (player = false): TabletopState => ({ campaign: demoCampaign, role: player ? "PLAYER" : "OWNER", scene: demoScene, overlays: demoOverlays, tokens: player ? demoTokens.filter((token) => token.visible) : demoTokens, characters: demoCharacters, monsterTemplates: [demoTemplate], monsterInstances: player ? [] : demoMonsters, combat: demoCombat, fogRegions: [], selectedTokenId: null, activeFogTool: null, placement: null, attackSelection: null, attackEvent: null, previewPlayerView: false, shiftIntel: false, connected: false });
