export type CampaignRole = "OWNER" | "DM" | "PLAYER" | "SPECTATOR";
export type TokenType = "PLAYER" | "MONSTER" | "NPC";
export type GridType = "SQUARE" | "GRIDLESS";
export type OverlayKind = "PROP" | "EFFECT";
export type AttackPreset = "MELEE" | "RANGED" | "SPELL" | "SNEAK_ATTACK" | "SMITE" | "DRUID" | "WIZARD";

export interface Campaign { id: string; name: string; joinCode: string; ownerId: string; role: CampaignRole; memberCount: number; updatedAt: string; }
export type SceneLighting = "DAY" | "MIDDAY" | "NIGHT";
export interface Scene { id: string; campaignId: string; mapId: string | null; name: string; mapUrl: string | null; width: number; height: number; gridType: GridType; gridSize: number; feetPerCell: number; gridColor: string; gridOpacity: number; gridLineWidth: number; active: boolean; revealed: boolean; mapX: number; mapY: number; mapScale: number; gridOffsetX: number; gridOffsetY: number; lighting: SceneLighting; playerCameraX: number | null; playerCameraY: number | null; playerCameraZoom: number; }
export interface SceneOverlay { id: string; sceneId: string; name: string; imageUrl: string; kind: OverlayKind; x: number; y: number; width: number; height: number; rotation: number; opacity: number; zIndex: number; visible: boolean; locked: boolean; }
export interface SceneZoneMarker { id:string; campaignId:string; sceneId:string; label:string; x:number; y:number; radiusFt:number; color:string; opacity:number; visible:boolean; createdAt:string; updatedAt:string; }
export type SceneLinkAudioMode = "KEEP" | "PLAY" | "STOP";
export interface SceneLink { id: string; sceneId: string; destinationSceneId: string; label: string; x: number; y: number; musicMode: SceneLinkAudioMode; musicTrackId: string | null; musicLoop: boolean; musicNextTrackId: string | null; musicNextLoop: boolean; ambienceMode: SceneLinkAudioMode; ambienceTrackId: string | null; ambienceLoop: boolean; }
export interface SceneDiscoverable { id: string; campaignId: string; sceneId: string; name: string; storagePath?: string | null; imageUrl?: string | null; x: number; y: number; hidden: boolean; discoveredAt: string | null; discoveredBy: string | null; createdAt: string; }
export interface NpcTemplate { id:string; name:string; imageUrl:string|null; imagePath?:string|null; createdAt:string; updatedAt:string; }
export interface Token { id: string; sceneId: string; referenceId: string | null; ownerUserId: string | null; type: TokenType; displayName: string; imageUrl: string | null; imagePath?: string | null; x: number; y: number; size: number; rotation: number; visible: boolean; locked: boolean; conditions: string[]; }
export type PatrolMode = "LOOP" | "PING_PONG" | "ONCE";
export interface PatrolWaypoint { id: string; x: number; y: number; }
export interface TokenPatrol { id: string; tokenId: string; sceneId: string; mode: PatrolMode; active: boolean; speed: number; waypointPauseMs: number; pauseDuringCombat: boolean; currentWaypoint: number; direction: 1 | -1; waypoints: PatrolWaypoint[]; createdAt: string; updatedAt: string; }
export interface TokenMotionSegment { tokenId:string; sceneId:string; fromX:number; fromY:number; toX:number; toY:number; startedAt:string; durationMs:number; revision:number; active:boolean; }
export type TokenInteractionType = "DIALOGUE" | "SHOP" | "BOTH";
export interface NpcShopItem { id:string; interactionId:string; name:string; description:string; priceGp:number; quantity:number|null; sortOrder:number; }
export interface TokenInteraction { tokenId:string; campaignId:string; enabled:boolean; type:TokenInteractionType; displayName:string; dialogueText:string; dialoguePages:string[]; shopItems:NpcShopItem[]; }
export type MonsterAttackType = "MELEE" | "RANGED" | "MELEE_OR_RANGED" | "SPELL" | "OTHER";
export interface DamageComponent { average: number | null; dice: string; flatBonus: number; damageType: string; }
export interface MonsterUsage { kind: "RECHARGE" | "PER_DAY"; value?: string; uses?: number; each?: boolean; }
export interface MonsterSave { ability: "STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA"; dc: number; }
export interface MonsterSpellcasting { actionName?: string; ability: string | null; saveDc: number | null; attackBonus: number | null; spells: { frequency: string; spells: string[] }[]; }
export interface MonsterAction { name: string; description: string; kind?: "ACTION" | "MULTIATTACK"; usage?: MonsterUsage | null; attackType?: MonsterAttackType; attackBonus?: number | null; reach?: number | null; range?: { normal: number; long: number | null; unit: "ft" } | null; damage?: DamageComponent[]; save?: MonsterSave | null; conditions?: string[]; effects?: string[]; variants?: MonsterAction[]; spellcasting?: MonsterSpellcasting; multiattack?: { count?: number; options?: string; description: string }; }
export interface AbilityScores { str: number; dex: number; con: number; int: number; wis: number; cha: number; }
export interface MovementSpeeds { walk: number; fly: number; swim: number; climb: number; burrow: number; hover: boolean; }
export interface MonsterTemplate { id: string; name: string; imageUrl: string | null; imagePath?: string | null; creatureSize: string; creatureType: string; maxHp: number; hpFormula: string | null; ac: number; speed: number; movement: MovementSpeeds; initiative: { modifier: number | null; score: number | null }; abilities: AbilityScores; savingThrows: Record<string, number>; skills: Record<string, number>; damageVulnerabilities: string[]; damageResistances: string[]; damageImmunities: string[]; conditionImmunities: string[]; senses: { name: string; range?: number; unit?: string }[]; passivePerception: number | null; languages: string[]; notes: string; traits: MonsterAction[]; actions: MonsterAction[]; bonusActions: MonsterAction[]; reactions: MonsterAction[]; legendaryActions: MonsterAction[]; legendaryActionUses: number | null; spellcasting: MonsterSpellcasting[]; }
export interface MonsterInstance { id: string; campaignId: string; templateId: string; customName: string; currentHp: number; maxHp: number; ac: number; conditions: string[]; visible: boolean; notes: string; dead: boolean; hpFormulaOverride: string | null; damageDiceOverrides: Record<string, string>; template?: MonsterTemplate; }
export interface Character { id: string; campaignId: string; ownerId: string; name: string; imageUrl: string | null; imagePath?: string | null; currentHp: number; maxHp: number; tempHp: number; ac: number; speed: number; abilities: AbilityScores; allowedAttackPresets: AttackPreset[]; passivePerception: number; passiveInvestigation: number; passiveInsight: number; notes: string; conditions: string[]; }
export interface InitiativeEntry { id: string; combatSessionId: string; tokenId: string | null; monsterInstanceId: string | null; characterId: string | null; name: string; imageUrl: string | null; initiative: number; sortOrder: number; groupKey: string | null; groupCount: number; }
export interface CombatSession { id: string; campaignId: string; sceneId: string; active: boolean; round: number; currentIndex: number; entries: InitiativeEntry[]; }
export type Placement = { kind: "CHARACTER" | "MONSTER" | "NPC" | "DISCOVERABLE"; referenceId: string; name: string; imageUrl: string | null; } | { kind: "CHARACTERS"; referenceIds: string[]; name: string; imageUrl: null; } | { kind: "SCENE_LINK"; destinationSceneId: string; name: string; imageUrl: null; } | { kind:"ZONE_MARKER"; name:string; radiusFt:number; color:string; imageUrl:null; };
export interface AttackAnimationEvent { id: string; campaignId: string; attackerTokenId: string; targetTokenId: string; preset: AttackPreset; color:string|null; createdAt: string; }
export interface AttackSelection { attackerTokenId: string; preset: AttackPreset; color:string|null; }
export type CinematicStep =
  | { at: number; duration?: number; type: "SCREEN_SHAKE" | "FLASH" | "DARKEN" | "VIGNETTE" | "UI_FADE_OUT" | "UI_FADE_IN" | "TITLE" | "LOCK_INTERACTION" | "LETTERBOX" | "COLOR_WASH" | "BLUR"; intensity?: number; color?: string; text?: string }
  | { at: number; duration?: number; type: "CAMERA_FOCUS_TOKEN"; tokenId: string; zoom?: number; intensity?: number; persistCamera?: boolean }
  | { at: number; duration?: number; type: "TOKEN_SHAKE" | "TOKEN_PULSE" | "TOKEN_FADE" | "TOKEN_FADE_IN" | "TOKEN_RISE" | "IMPACT" | "TOKEN_GLOW"; tokenId: string; zoom?: number; intensity?: number; color?: string }
  | { at: number; duration?: number; type: "CAMERA_FOCUS_POINT"; x?: number; y?: number; zoom?: number; intensity?: number; persistCamera?: boolean }
  | { at: number; duration?: number; type: "MAP_SHAKE"; x?: number; y?: number; zoom?: number; intensity?: number };
export interface CinematicEvent { id: string; campaignId: string; name: string; duration: number; steps: CinematicStep[]; createdAt: string; completed?: boolean; }
export interface DiceRoll { id: string; campaignId: string; rollerUserId: string; rollerRole: CampaignRole; rollerDisplayName: string | null; sides: number; quantity: number; results: number[]; total: number; createdAt: string; }
export interface TabletopState { campaign: Campaign; role: CampaignRole; scene: Scene; scenes: Scene[]; sceneLinks: SceneLink[]; discoverables: SceneDiscoverable[]; treasure: SceneDiscoverable[]; discoveryReveal: SceneDiscoverable | null; overlays: SceneOverlay[]; zoneMarkers: SceneZoneMarker[]; tokens: Token[]; transientTokenIds: string[]; motionSegments: TokenMotionSegment[]; tokenInteractions: TokenInteraction[]; patrols: TokenPatrol[]; patrolEditTokenId: string | null; characters: Character[]; npcTemplates: NpcTemplate[]; monsterTemplates: MonsterTemplate[]; monsterInstances: MonsterInstance[]; combat: CombatSession; diceRolls: DiceRoll[]; selectedTokenId: string | null; selectedTokenIds: string[]; activeInteractionTokenId: string | null; placement: Placement | null; attackSelection: AttackSelection | null; attackEvent: AttackAnimationEvent | null; cinematicEvent: CinematicEvent | null; dreadActive: boolean; previewPlayerView: boolean; shiftIntel: boolean; connected: boolean; }

export const CONDITION_OPTIONS = ["Poisoned","Prone","Restrained","Stunned","Blinded","Charmed","Frightened","Grappled","Incapacitated","Invisible"] as const;
export const isDmRole = (role: CampaignRole) => role === "OWNER" || role === "DM";
