import type { Campaign, CampaignRole, Character, MonsterTemplate, Scene } from "../domain/types";
import { isSupabaseConfigured, supabase } from "../lib/supabase";

export interface CampaignMember { userId: string; displayName: string; role: CampaignRole; joinedAt: string; }
export interface CampaignNote { id: string; title: string; body: string; }
export interface PreparedEncounter { id: string; name: string; notes: string; members: { id: string; templateId: string; quantity: number }[]; }
export interface SetupData { campaign: Campaign; members: CampaignMember[]; scenes: Scene[]; characters: Character[]; templates: MonsterTemplate[]; encounters: PreparedEncounter[]; notes: CampaignNote[]; }

type Row = Record<string, unknown>;
const asScene = (r: Row): Scene => ({ id:String(r.id),campaignId:String(r.campaign_id),mapId:r.map_id?String(r.map_id):null,name:String(r.name),mapUrl:r.map_url?String(r.map_url):null,width:Number(r.width),height:Number(r.height),gridType:r.grid_type as Scene["gridType"],gridSize:Number(r.grid_size),feetPerCell:Number(r.feet_per_cell),gridColor:String(r.grid_color),gridOpacity:Number(r.grid_opacity),fogEnabled:Boolean(r.fog_enabled),fogCovered:Boolean(r.fog_covered),active:Boolean(r.active) });
const asCharacter = (r: Row, note = ""): Character => ({ id:String(r.id),campaignId:String(r.campaign_id),ownerId:String(r.owner_id),name:String(r.name),imageUrl:r.image_url?String(r.image_url):null,imagePath:r.image_path?String(r.image_path):null,currentHp:Number(r.current_hp),maxHp:Number(r.max_hp),ac:Number(r.ac),speed:Number(r.speed),passivePerception:Number(r.passive_perception),passiveInvestigation:Number(r.passive_investigation),passiveInsight:Number(r.passive_insight),notes:note,conditions:(r.conditions as string[]) ?? [] });
const asTemplate = (r: Row): MonsterTemplate => ({ id:String(r.id),campaignId:String(r.campaign_id),name:String(r.name),imageUrl:r.image_url?String(r.image_url):null,imagePath:r.image_path?String(r.image_path):null,maxHp:Number(r.max_hp),ac:Number(r.ac),speed:Number(r.speed),abilities:r.abilities as MonsterTemplate["abilities"],notes:String(r.notes ?? ""),traits:r.traits as MonsterTemplate["traits"],actions:r.actions as MonsterTemplate["actions"],bonusActions:r.bonus_actions as MonsterTemplate["bonusActions"],reactions:r.reactions as MonsterTemplate["reactions"] });
const signed = async (path: string | null | undefined) => { if (!path) return null; const { data, error } = await supabase.storage.from("campaign-assets").createSignedUrl(path, 60 * 60 * 12); if (error) throw error; return data.signedUrl; };
const fail = (error: { message?: string } | null, fallback: string) => { if (error) throw new Error(error.message || fallback); };

export const campaignSetupService = {
  async load(campaignId: string): Promise<SetupData> {
    const [{data:campaign,error:campaignError},{data:memberRows,error:memberError},{data:sceneRows,error:sceneError},{data:characterRows,error:characterError},{data:templateRows,error:templateError},{data:encounterRows,error:encounterError},{data:noteRows,error:noteError}] = await Promise.all([
      supabase.from("campaigns").select("id,name,join_code,owner_id,updated_at").eq("id",campaignId).single(),
      supabase.from("campaign_members").select("user_id,role,joined_at,profiles(display_name)").eq("campaign_id",campaignId).order("joined_at"),
      supabase.from("scenes").select("*").eq("campaign_id",campaignId).order("created_at"),
      supabase.from("characters").select("*").eq("campaign_id",campaignId).order("name"),
      supabase.from("monster_templates").select("*").eq("campaign_id",campaignId).order("name"),
      supabase.from("encounters").select("id,name,notes,encounter_members(id,monster_template_id,quantity)").eq("campaign_id",campaignId).order("updated_at",{ascending:false}),
      supabase.from("campaign_notes").select("id,title,body").eq("campaign_id",campaignId).order("updated_at",{ascending:false}),
    ]);
    fail(campaignError,"Could not load campaign."); fail(memberError,"Could not load players."); fail(sceneError,"Could not load scenes."); fail(characterError,"Could not load characters."); fail(templateError,"Could not load monster templates."); fail(encounterError,"Could not load encounters."); fail(noteError,"Could not load notes."); if (!campaign) throw new Error("Campaign was not found.");
    const characterNotes = await Promise.all(((characterRows ?? []) as Row[]).map(async c => { const {data} = await supabase.from("character_private").select("notes").eq("character_id",String(c.id)).maybeSingle(); return [String(c.id),String(data?.notes ?? "")] as const; }));
    const noteByCharacter = new Map(characterNotes);
    const scenes = await Promise.all(((sceneRows ?? []) as Row[]).map(async row => { if (row.map_id) { const {data:map}=await supabase.from("maps").select("storage_path").eq("id",String(row.map_id)).maybeSingle(); const url=await signed(map?.storage_path); if(url)row.map_url=url; } return asScene(row); }));
    const characters = await Promise.all(((characterRows ?? []) as Row[]).map(async row => { const path=row.image_path?String(row.image_path):null; const url=await signed(path); if(url)row.image_url=url; return asCharacter(row,noteByCharacter.get(String(row.id))); }));
    const templates = await Promise.all(((templateRows ?? []) as Row[]).map(async row => { const path=row.image_path?String(row.image_path):null; const url=await signed(path); if(url)row.image_url=url; return asTemplate(row); }));
    const members=((memberRows??[]) as Row[]).map(row=>({userId:String(row.user_id),displayName:String((row.profiles as Row|null)?.display_name??"Adventurer"),role:row.role as CampaignRole,joinedAt:String(row.joined_at)}));
    const { data: { user } } = await supabase.auth.getUser();
    const role=members.find(member=>member.userId===user?.id)?.role??"SPECTATOR";
    return { campaign:{id:String(campaign.id),name:String(campaign.name),joinCode:String(campaign.join_code),ownerId:String(campaign.owner_id),role,memberCount:members.length,updatedAt:String(campaign.updated_at)}, members, scenes,characters,templates,encounters:((encounterRows??[]) as Row[]).map(row=>({id:String(row.id),name:String(row.name),notes:String(row.notes??""),members:((row.encounter_members??[]) as Row[]).map(m=>({id:String(m.id),templateId:String(m.monster_template_id),quantity:Number(m.quantity)}))})),notes:((noteRows??[]) as Row[]).map(row=>({id:String(row.id),title:String(row.title),body:String(row.body)})) };
  },
  async uploadImage(campaignId: string, category: string, file: File) { const id=crypto.randomUUID(); const path=`${campaignId}/${category}/${id}-${file.name.replace(/[^a-z0-9.-]/gi,"-")}`; const {error}=await supabase.storage.from("campaign-assets").upload(path,file); fail(error,"Image upload failed."); return {path,url:await signed(path)}; },
  async imageDimensions(file: File) { const url=URL.createObjectURL(file); try { const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url;}); return {width:image.naturalWidth,height:image.naturalHeight}; } finally { URL.revokeObjectURL(url); } },
  async saveCharacter(campaignId: string, input: Omit<Character,"id"|"campaignId"> & { id?: string; imagePath?: string | null }) { const payload={campaign_id:campaignId,owner_id:input.ownerId,name:input.name,image_url:input.imageUrl,image_path:input.imagePath??null,current_hp:input.currentHp,max_hp:input.maxHp,ac:input.ac,speed:input.speed,passive_perception:input.passivePerception,passive_investigation:input.passiveInvestigation,passive_insight:input.passiveInsight,conditions:input.conditions}; const result=input.id?await supabase.from("characters").update(payload).eq("id",input.id).select("id").single():await supabase.from("characters").insert(payload).select("id").single(); fail(result.error,"Could not save character."); if (!result.data) throw new Error("Character save returned no record."); const {error}=await supabase.from("character_private").upsert({character_id:result.data.id,notes:input.notes}); fail(error,"Could not save character notes."); },
  async deleteCharacter(id: string) { const {error}=await supabase.from("characters").delete().eq("id",id); fail(error,"Could not delete character."); },
  async saveTemplate(campaignId: string, input: Omit<MonsterTemplate,"id"|"campaignId"> & { id?: string; imagePath?: string | null }) { const payload={campaign_id:campaignId,name:input.name,image_url:input.imageUrl,image_path:input.imagePath??null,max_hp:input.maxHp,ac:input.ac,speed:input.speed,abilities:input.abilities,notes:input.notes,traits:input.traits,actions:input.actions,bonus_actions:input.bonusActions,reactions:input.reactions}; const result=input.id?await supabase.from("monster_templates").update(payload).eq("id",input.id):await supabase.from("monster_templates").insert(payload); fail(result.error,"Could not save monster template."); },
  async deleteTemplate(id: string) { const {error}=await supabase.from("monster_templates").delete().eq("id",id); fail(error,"This monster template is still used by placed creatures."); },
  async createScene(campaignId: string, name: string) { const { count, error:countError }=await supabase.from("scenes").select("id",{count:"exact",head:true}).eq("campaign_id",campaignId).eq("active",true); fail(countError,"Could not create scene."); const {data,error}=await supabase.from("scenes").insert({campaign_id:campaignId,name,active:count===0}).select("id").single(); fail(error,"Could not create scene."); if (!data) throw new Error("Scene creation returned no record."); return String(data.id); },
  async saveScene(id: string, patch: Partial<Scene>) { const {error}=await supabase.from("scenes").update({name:patch.name,width:patch.width,height:patch.height,grid_type:patch.gridType,grid_size:patch.gridSize,feet_per_cell:patch.feetPerCell,grid_color:patch.gridColor,grid_opacity:patch.gridOpacity,fog_enabled:patch.fogEnabled,fog_covered:patch.fogCovered}).eq("id",id); fail(error,"Could not save scene."); },
  async activateScene(campaignId: string, sceneId: string) { let result=await supabase.from("scenes").update({active:false}).eq("campaign_id",campaignId).eq("active",true); fail(result.error,"Could not switch scenes."); result=await supabase.from("scenes").update({active:true}).eq("id",sceneId); fail(result.error,"Could not switch scenes."); },
  async deleteScene(id: string) { const {error}=await supabase.from("scenes").delete().eq("id",id); fail(error,"Could not delete scene."); },
  async uploadMap(campaignId: string, sceneId: string, file: File) { const dims=await this.imageDimensions(file); const {path}=await this.uploadImage(campaignId,"maps",file); const {data:map,error:mapError}=await supabase.from("maps").insert({campaign_id:campaignId,name:file.name,storage_path:path,width:dims.width,height:dims.height}).select("id").single(); fail(mapError,"Map upload failed."); if (!map) throw new Error("Map upload returned no record."); const {error}=await supabase.from("scenes").update({map_id:map.id,name:file.name.replace(/\.[^.]+$/, ""),width:dims.width,height:dims.height}).eq("id",sceneId); fail(error,"Could not attach map to scene."); },
  async saveMemberRole(campaignId: string,userId: string,role: CampaignRole) { const {error}=await supabase.from("campaign_members").update({role}).eq("campaign_id",campaignId).eq("user_id",userId); fail(error,"Could not update member role."); },
  async saveEncounter(campaignId:string,input:{id?:string;name:string;notes:string;members:{id?:string;templateId:string;quantity:number}[]}) { const result=input.id?await supabase.from("encounters").update({name:input.name,notes:input.notes}).eq("id",input.id).select("id").single():await supabase.from("encounters").insert({campaign_id:campaignId,name:input.name,notes:input.notes}).select("id").single(); fail(result.error,"Could not save encounter."); if (!result.data) throw new Error("Encounter save returned no record."); const encounterId=String(result.data.id); const {error:removeError}=await supabase.from("encounter_members").delete().eq("encounter_id",encounterId); fail(removeError,"Could not update encounter."); if(input.members.length){const {error}=await supabase.from("encounter_members").insert(input.members.map(member=>({encounter_id:encounterId,monster_template_id:member.templateId,quantity:member.quantity})));fail(error,"Could not update encounter.");} },
  async deleteEncounter(id:string) { const {error}=await supabase.from("encounters").delete().eq("id",id);fail(error,"Could not delete encounter."); },
  async saveNote(campaignId:string,note:CampaignNote) { const result=note.id?await supabase.from("campaign_notes").update({title:note.title,body:note.body}).eq("id",note.id):await supabase.from("campaign_notes").insert({campaign_id:campaignId,title:note.title,body:note.body});fail(result.error,"Could not save note."); },
};

export const configuredSetup = isSupabaseConfigured;
