import type { Campaign, CampaignRole, Character, MonsterTemplate, NpcTemplate, Scene } from "../domain/types";
import { isSupabaseConfigured, supabase } from "../lib/supabase";

export interface CampaignMember { userId: string; displayName: string; role: CampaignRole; joinedAt: string; }
export interface CampaignNote { id: string; title: string; body: string; }
export interface PreparedEncounter { id: string; name: string; notes: string; members: { id: string; templateId: string; quantity: number }[]; }
export interface SetupData { campaign: Campaign; members: CampaignMember[]; scenes: Scene[]; characters: Character[]; npcTemplates: NpcTemplate[]; templates: MonsterTemplate[]; encounters: PreparedEncounter[]; notes: CampaignNote[]; }

type Row = Record<string, unknown>;
const asScene = (r: Row): Scene => ({ id:String(r.id),campaignId:String(r.campaign_id),mapId:r.map_id?String(r.map_id):null,name:String(r.name),mapUrl:r.map_url?String(r.map_url):null,width:Number(r.width),height:Number(r.height),gridType:r.grid_type as Scene["gridType"],gridSize:Number(r.grid_size),feetPerCell:Number(r.feet_per_cell),gridColor:String(r.grid_color),gridOpacity:Number(r.grid_opacity),gridLineWidth:Number(r.grid_line_width??1),active:Boolean(r.active),revealed:Boolean(r.revealed),mapX:Number(r.map_x??0),mapY:Number(r.map_y??0),mapScale:Number(r.map_scale??1),gridOffsetX:Number(r.grid_offset_x??0),gridOffsetY:Number(r.grid_offset_y??0),lighting:(r.lighting==="NIGHT"||r.lighting==="DARK"?"NIGHT":r.lighting==="MIDDAY"||r.lighting==="DIM"?"MIDDAY":"DAY") as Scene["lighting"],playerCameraX:r.player_camera_x===null||r.player_camera_x===undefined?null:Number(r.player_camera_x),playerCameraY:r.player_camera_y===null||r.player_camera_y===undefined?null:Number(r.player_camera_y),playerCameraZoom:Number(r.player_camera_zoom??1) });
const asCharacter = (r: Row, note = ""): Character => ({ id:String(r.id),campaignId:String(r.campaign_id),ownerId:String(r.owner_id),name:String(r.name),imageUrl:r.image_url?String(r.image_url):null,imagePath:r.image_path?String(r.image_path):null,currentHp:Number(r.current_hp),maxHp:Number(r.max_hp),tempHp:Number(r.temp_hp??0),ac:Number(r.ac),speed:Number(r.speed),abilities:{str:Number(r.strength??10),dex:Number(r.dexterity??10),con:Number(r.constitution??10),int:Number(r.intelligence??10),wis:Number(r.wisdom??10),cha:Number(r.charisma??10)},passivePerception:Number(r.passive_perception),passiveInvestigation:Number(r.passive_investigation),passiveInsight:Number(r.passive_insight),notes:note,conditions:(r.conditions as string[]) ?? [] });
const asNpcTemplate = (r:Row):NpcTemplate => ({id:String(r.id),name:String(r.name),imageUrl:r.image_url?String(r.image_url):null,imagePath:r.image_path?String(r.image_path):null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)});
const asTemplate = (r: Row): MonsterTemplate => ({ id:String(r.id),name:String(r.name),imageUrl:r.image_url?String(r.image_url):null,imagePath:r.image_path?String(r.image_path):null,creatureSize:String(r.creature_size ?? "Medium"),creatureType:String(r.creature_type ?? ""),maxHp:Number(r.max_hp),hpFormula:r.hp_formula?String(r.hp_formula):null,ac:Number(r.ac),speed:Number(r.speed),movement:(r.movement as MonsterTemplate["movement"]) ?? {walk:Number(r.speed),fly:0,swim:0,climb:0,burrow:0,hover:false},initiative:(r.initiative as MonsterTemplate["initiative"]) ?? {modifier:null,score:null},abilities:r.abilities as MonsterTemplate["abilities"],savingThrows:(r.saving_throws as MonsterTemplate["savingThrows"]) ?? {},skills:(r.skills as MonsterTemplate["skills"]) ?? {},damageVulnerabilities:(r.damage_vulnerabilities as string[]|null) ?? [],damageResistances:(r.damage_resistances as string[]|null) ?? [],damageImmunities:(r.damage_immunities as string[]|null) ?? [],conditionImmunities:(r.condition_immunities as string[]|null) ?? [],senses:(r.senses as MonsterTemplate["senses"]) ?? [],passivePerception:r.passive_perception===null||r.passive_perception===undefined?null:Number(r.passive_perception),languages:(r.languages as string[]|null) ?? [],notes:String(r.notes ?? ""),traits:(r.traits as MonsterTemplate["traits"]) ?? [],actions:(r.actions as MonsterTemplate["actions"]) ?? [],bonusActions:(r.bonus_actions as MonsterTemplate["bonusActions"]) ?? [],reactions:(r.reactions as MonsterTemplate["reactions"]) ?? [],legendaryActions:(r.legendary_actions as MonsterTemplate["legendaryActions"]) ?? [],legendaryActionUses:r.legendary_action_uses===null||r.legendary_action_uses===undefined?null:Number(r.legendary_action_uses),spellcasting:(r.spellcasting as MonsterTemplate["spellcasting"]) ?? [] });
const signed = async (path: string | null | undefined) => { if (!path) return null; const { data, error } = await supabase.storage.from("campaign-assets").createSignedUrl(path, 60 * 60 * 12); return error ? null : data?.signedUrl ?? null; };
const fail = (error: { message?: string } | null, fallback: string) => { if (error) throw new Error(error.message || fallback); };

export const campaignSetupService = {
  async load(campaignId: string): Promise<SetupData> {
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    fail(userError,"Sign in is required to load campaign setup."); if (!user) throw new Error("Sign in is required to load campaign setup.");
    const { data: membership, error: membershipError } = await supabase.from("campaign_members").select("role").eq("campaign_id",campaignId).eq("user_id",user.id).maybeSingle();
    fail(membershipError,"Could not verify campaign membership."); if (!membership) throw new Error("You are not a member of this campaign.");
    const role=membership.role as CampaignRole; const dm=role==="OWNER"||role==="DM";
    const [{data:campaign,error:campaignError},{data:memberRows,error:memberError},{data:sceneRows,error:sceneError},{data:characterRows,error:characterError},{data:npcTemplateRows,error:npcTemplateError},{data:templateRows,error:templateError},{data:encounterRows,error:encounterError},{data:noteRows,error:noteError}] = await Promise.all([
      supabase.from("campaigns").select("id,name,join_code,owner_id,updated_at").eq("id",campaignId).single(),
      supabase.from("campaign_members").select("user_id,role,joined_at,profiles(display_name)").eq("campaign_id",campaignId).order("joined_at"),
      dm?supabase.from("scenes").select("*").eq("campaign_id",campaignId).order("created_at"):supabase.from("scenes").select("*").eq("campaign_id",campaignId).eq("active",true).eq("revealed",true).order("created_at"),
      supabase.from("characters").select("id,campaign_id,owner_id,name,image_url,image_path,current_hp,max_hp,temp_hp,ac,speed,passive_perception,passive_investigation,passive_insight,conditions").eq("campaign_id",campaignId).order("name"),
      dm?supabase.from("npc_templates").select("*").order("name"):Promise.resolve({data:[],error:null}),
      dm?supabase.from("monster_templates").select("*").order("name"):Promise.resolve({data:[],error:null}),
      dm?supabase.from("encounters").select("id,name,notes,encounter_members(id,monster_template_id,quantity)").eq("campaign_id",campaignId).order("updated_at",{ascending:false}):Promise.resolve({data:[],error:null}),
      dm?supabase.from("campaign_notes").select("id,title,body").eq("campaign_id",campaignId).order("updated_at",{ascending:false}):Promise.resolve({data:[],error:null}),
    ]);
    fail(campaignError,"Could not load campaign."); fail(memberError,"Could not load players."); fail(sceneError,"Could not load scenes."); fail(characterError,"Could not load characters."); fail(npcTemplateError,"Could not load NPC templates."); fail(templateError,"Could not load monster templates."); fail(encounterError,"Could not load encounters."); fail(noteError,"Could not load notes."); if (!campaign) throw new Error("Campaign was not found.");
    const characterNotes = dm?await Promise.all(((characterRows ?? []) as Row[]).map(async c => { const {data} = await supabase.from("character_private").select("notes").eq("character_id",String(c.id)).maybeSingle(); return [String(c.id),String(data?.notes ?? "")] as const; })):[];
    const noteByCharacter = new Map(characterNotes);
    const scenes = await Promise.all(((sceneRows ?? []) as Row[]).map(async row => { if (row.map_id) { const {data:map}=await supabase.from("maps").select("storage_path").eq("id",String(row.map_id)).maybeSingle(); const url=await signed(map?.storage_path); if(url)row.map_url=url; } return asScene(row); }));
    const characters = await Promise.all(((characterRows ?? []) as Row[]).map(async row => { const path=row.image_path?String(row.image_path):null; const url=await signed(path); if(url)row.image_url=url; return asCharacter(row,noteByCharacter.get(String(row.id))); }));
    const npcTemplates = await Promise.all(((npcTemplateRows ?? []) as Row[]).map(async row => { const path=row.image_path?String(row.image_path):null; const url=await signed(path); if(url)row.image_url=url; return asNpcTemplate(row); }));
    const templates = await Promise.all(((templateRows ?? []) as Row[]).map(async row => { const path=row.image_path?String(row.image_path):null; const url=await signed(path); if(url)row.image_url=url; return asTemplate(row); }));
    const members=((memberRows??[]) as Row[]).map(row=>({userId:String(row.user_id),displayName:String((row.profiles as Row|null)?.display_name??"Adventurer"),role:row.role as CampaignRole,joinedAt:String(row.joined_at)}));
    return { campaign:{id:String(campaign.id),name:String(campaign.name),joinCode:String(campaign.join_code),ownerId:String(campaign.owner_id),role,memberCount:members.length,updatedAt:String(campaign.updated_at)}, members, scenes,characters,npcTemplates,templates,encounters:((encounterRows??[]) as Row[]).map(row=>({id:String(row.id),name:String(row.name),notes:String(row.notes??""),members:((row.encounter_members??[]) as Row[]).map(m=>({id:String(m.id),templateId:String(m.monster_template_id),quantity:Number(m.quantity)}))})),notes:((noteRows??[]) as Row[]).map(row=>({id:String(row.id),title:String(row.title),body:String(row.body)})) };
  },
  async uploadImage(campaignId: string, category: string, file: File) { const id=crypto.randomUUID(); const path=`${campaignId}/${category}/${id}-${file.name.replace(/[^a-z0-9.-]/gi,"-")}`; const {error}=await supabase.storage.from("campaign-assets").upload(path,file); fail(error,"Image upload failed."); return {path,url:await signed(path)}; },
  async imageDimensions(file: File) { const url=URL.createObjectURL(file); try { const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url;}); return {width:image.naturalWidth,height:image.naturalHeight}; } finally { URL.revokeObjectURL(url); } },
  async saveCharacter(campaignId: string, input: Omit<Character,"id"|"campaignId"> & { id?: string; imagePath?: string | null }) { const payload={campaign_id:campaignId,owner_id:input.ownerId,name:input.name,image_url:input.imageUrl,image_path:input.imagePath??null,current_hp:input.currentHp,max_hp:input.maxHp,temp_hp:input.tempHp,ac:input.ac,speed:input.speed,strength:input.abilities.str,dexterity:input.abilities.dex,constitution:input.abilities.con,intelligence:input.abilities.int,wisdom:input.abilities.wis,charisma:input.abilities.cha,passive_perception:input.passivePerception,passive_investigation:input.passiveInvestigation,passive_insight:input.passiveInsight,conditions:input.conditions}; const result=input.id?await supabase.from("characters").update(payload).eq("id",input.id).select("id").single():await supabase.from("characters").insert(payload).select("id").single(); fail(result.error,"Could not save character."); if (!result.data) throw new Error("Character save returned no record."); const {error}=await supabase.from("character_private").upsert({character_id:result.data.id,notes:input.notes}); fail(error,"Could not save character notes."); },
  async deleteCharacter(id: string) { const {error}=await supabase.from("characters").delete().eq("id",id); fail(error,"Could not delete character."); },
  async saveNpcTemplate(input: { id?: string; name: string; imageUrl?: string | null; imagePath?: string | null }) { const payload={name:input.name,image_url:null,image_path:input.imagePath??null,updated_at:new Date().toISOString()}; const result=input.id?await supabase.from("npc_templates").update(payload).eq("id",input.id):await supabase.from("npc_templates").insert(payload); fail(result.error,"Could not save NPC."); },
  async deleteNpcTemplate(id:string) { const {data,error:loadError}=await supabase.from("npc_templates").select("image_path").eq("id",id).single(); fail(loadError,"Could not load NPC."); const {error}=await supabase.from("npc_templates").delete().eq("id",id); fail(error,"Could not delete NPC."); if(data?.image_path){const {error:assetError}=await supabase.storage.from("campaign-assets").remove([String(data.image_path)]); fail(assetError,"NPC deleted, but its old portrait could not be removed.");} },
  async saveTemplate(input: Omit<MonsterTemplate,"id"> & { id?: string; imagePath?: string | null }) { const payload={name:input.name,image_url:input.imageUrl,image_path:input.imagePath??null,creature_size:input.creatureSize,creature_type:input.creatureType,max_hp:input.maxHp,hp_formula:input.hpFormula,ac:input.ac,speed:input.speed,movement:input.movement,initiative:input.initiative,abilities:input.abilities,saving_throws:input.savingThrows,skills:input.skills,damage_vulnerabilities:input.damageVulnerabilities,damage_resistances:input.damageResistances,damage_immunities:input.damageImmunities,condition_immunities:input.conditionImmunities,senses:input.senses,passive_perception:input.passivePerception,languages:input.languages,notes:input.notes,traits:input.traits,actions:input.actions,bonus_actions:input.bonusActions,reactions:input.reactions,legendary_actions:input.legendaryActions,legendary_action_uses:input.legendaryActionUses,spellcasting:input.spellcasting}; const result=input.id?await supabase.from("monster_templates").update(payload).eq("id",input.id):await supabase.from("monster_templates").insert(payload); fail(result.error,"Could not save monster template."); },
  async deleteTemplate(id: string) { const {error}=await supabase.from("monster_templates").delete().eq("id",id); fail(error,"This monster template is still used by placed creatures."); },
  async createScene(campaignId: string, name: string) { const { count, error:countError }=await supabase.from("scenes").select("id",{count:"exact",head:true}).eq("campaign_id",campaignId).eq("active",true); fail(countError,"Could not create scene."); const firstScene=count===0; const {data,error}=await supabase.from("scenes").insert({campaign_id:campaignId,name,active:firstScene,revealed:firstScene}).select("id").single(); fail(error,"Could not create scene."); if (!data) throw new Error("Scene creation returned no record."); return String(data.id); },
  async saveScene(id: string, patch: Partial<Scene>) { const {error}=await supabase.from("scenes").update({name:patch.name,width:patch.width,height:patch.height,grid_type:patch.gridType,grid_size:patch.gridSize,feet_per_cell:patch.feetPerCell,grid_color:patch.gridColor,grid_opacity:patch.gridOpacity,map_x:patch.mapX,map_y:patch.mapY,map_scale:patch.mapScale,grid_offset_x:patch.gridOffsetX,grid_offset_y:patch.gridOffsetY,lighting:patch.lighting,player_camera_x:patch.playerCameraX,player_camera_y:patch.playerCameraY,player_camera_zoom:patch.playerCameraZoom}).eq("id",id); fail(error,"Could not save scene."); },
  async activateScene(_campaignId: string, sceneId: string) { const {error}=await supabase.rpc("make_scene_live",{p_scene_id:sceneId}); fail(error,"Could not switch scenes."); },
  async setSceneRevealed(sceneId: string, revealed: boolean) { const {error}=await supabase.from("scenes").update({revealed}).eq("id",sceneId); fail(error,"Could not update scene visibility."); },
  async deleteScene(id: string) { const {error}=await supabase.from("scenes").delete().eq("id",id); fail(error,"Could not delete scene."); },
  async uploadMap(campaignId: string, sceneId: string, file: File) { const dims=await this.imageDimensions(file); const {path}=await this.uploadImage(campaignId,"maps",file); const {data:map,error:mapError}=await supabase.from("maps").insert({campaign_id:campaignId,name:file.name,storage_path:path,width:dims.width,height:dims.height}).select("id").single(); fail(mapError,"Map upload failed."); if (!map) throw new Error("Map upload returned no record."); const {error}=await supabase.from("scenes").update({map_id:map.id,name:file.name.replace(/\.[^.]+$/, ""),width:dims.width,height:dims.height}).eq("id",sceneId); fail(error,"Could not attach map to scene."); },
  async saveMemberRole(campaignId: string,userId: string,role: CampaignRole) { const {error}=await supabase.from("campaign_members").update({role}).eq("campaign_id",campaignId).eq("user_id",userId); fail(error,"Could not update member role."); },
  async saveEncounter(campaignId:string,input:{id?:string;name:string;notes:string;members:{id?:string;templateId:string;quantity:number}[]}) { const result=input.id?await supabase.from("encounters").update({name:input.name,notes:input.notes}).eq("id",input.id).select("id").single():await supabase.from("encounters").insert({campaign_id:campaignId,name:input.name,notes:input.notes}).select("id").single(); fail(result.error,"Could not save encounter."); if (!result.data) throw new Error("Encounter save returned no record."); const encounterId=String(result.data.id); const {error:removeError}=await supabase.from("encounter_members").delete().eq("encounter_id",encounterId); fail(removeError,"Could not update encounter."); if(input.members.length){const {error}=await supabase.from("encounter_members").insert(input.members.map(member=>({encounter_id:encounterId,monster_template_id:member.templateId,quantity:member.quantity})));fail(error,"Could not update encounter.");} },
  async deleteEncounter(id:string) { const {error}=await supabase.from("encounters").delete().eq("id",id);fail(error,"Could not delete encounter."); },
  async saveNote(campaignId:string,note:CampaignNote) { const result=note.id?await supabase.from("campaign_notes").update({title:note.title,body:note.body}).eq("id",note.id):await supabase.from("campaign_notes").insert({campaign_id:campaignId,title:note.title,body:note.body});fail(result.error,"Could not save note."); },
};

export const configuredSetup = isSupabaseConfigured;
