import type { CampaignRole, Character, CombatSession, FogRegion, MonsterInstance, MonsterTemplate, Scene, SceneOverlay, TabletopState, Token } from "../domain/types";
import { isSupabaseConfigured, supabase } from "../lib/supabase";
import { createDemoState } from "../domain/demoData";

const asScene = (r: Record<string, unknown>): Scene => ({ id: String(r.id), campaignId: String(r.campaign_id), mapId: r.map_id ? String(r.map_id) : null, name: String(r.name), mapUrl: r.map_url ? String(r.map_url) : null, width: Number(r.width), height: Number(r.height), gridType: r.grid_type as Scene["gridType"], gridSize: Number(r.grid_size), feetPerCell: Number(r.feet_per_cell), gridColor: String(r.grid_color), gridOpacity: Number(r.grid_opacity), fogEnabled: Boolean(r.fog_enabled), fogCovered: Boolean(r.fog_covered), active: Boolean(r.active) });
const asToken = (r: Record<string, unknown>): Token => ({ id: String(r.id), sceneId: String(r.scene_id), referenceId: r.reference_id ? String(r.reference_id) : null, ownerUserId: r.owner_user_id ? String(r.owner_user_id) : null, type: r.type as Token["type"], displayName: String(r.display_name), imageUrl: r.image_url ? String(r.image_url) : null, imagePath: r.image_path ? String(r.image_path) : null, x: Number(r.x), y: Number(r.y), size: Number(r.size), rotation: Number(r.rotation), visible: Boolean(r.visible), locked: Boolean(r.locked), conditions: (r.conditions as string[] | null) ?? [] });
const asOverlay = (r: Record<string, unknown>): SceneOverlay => ({ id: String(r.id), sceneId: String(r.scene_id), name: String(r.name), imageUrl: String(r.image_url), kind: r.kind as SceneOverlay["kind"], x: Number(r.x), y: Number(r.y), width: Number(r.width), height: Number(r.height), rotation: Number(r.rotation), opacity: Number(r.opacity), zIndex: Number(r.z_index), visible: Boolean(r.visible), locked: Boolean(r.locked) });
const signTokenImage = async (token: Token) => { if (!token.imagePath) return token; const { data }=await supabase.storage.from("campaign-assets").createSignedUrl(token.imagePath,60*60*12); return data?.signedUrl?{...token,imageUrl:data.signedUrl}:token; };

export const tabletopService = {
  async load(campaignId: string, playerView = false): Promise<TabletopState> {
    if (!isSupabaseConfigured || campaignId === "demo") return createDemoState(playerView);
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError) throw userError;
    if (!user) throw new Error("Sign in is required to open this tabletop.");
    const [{ data: membership, error: memberError }, { data: campaign, error: campaignError }, { data: sceneRow, error: sceneError }] = await Promise.all([
      // Members can read the campaign roster. Filter to the signed-in user's row
      // before calling single(), otherwise a second player makes this query plural.
      supabase.from("campaign_members").select("role").eq("campaign_id", campaignId).eq("user_id", user.id).maybeSingle(),
      supabase.from("campaigns").select("id,name,join_code,owner_id,updated_at").eq("id", campaignId).single(),
      supabase.from("scenes").select("*").eq("campaign_id", campaignId).eq("active", true).single(),
    ]);
    if (memberError) throw memberError; if (!membership) throw new Error("You are not a member of this campaign."); if (campaignError) throw campaignError; if (sceneError) throw sceneError;
    const role = membership.role as CampaignRole; const scene = asScene(sceneRow as Record<string, unknown>);
    if (scene.mapId) { const { data: map } = await supabase.from("maps").select("storage_path").eq("id",scene.mapId).single(); if (map?.storage_path) { const { data: signed } = await supabase.storage.from("campaign-assets").createSignedUrl(map.storage_path,60*60*12); if (signed) scene.mapUrl=signed.signedUrl; } }
    const [{ data: tokenRows }, { data: overlayRows }, { data: characterRows }, { data: combatRow }, { data: fogRows }, { data: templateRows }] = await Promise.all([
      supabase.from("tokens").select("id,scene_id,reference_id,owner_user_id,type,display_name,image_url,image_path,x,y,size,rotation,visible,locked,conditions").eq("scene_id", scene.id),
      supabase.from("scene_overlays").select("*").eq("scene_id", scene.id).order("z_index"),
      supabase.from("characters_public").select("*").eq("campaign_id", campaignId),
      supabase.from("combat_sessions").select("*").eq("scene_id", scene.id).eq("active", true).maybeSingle(),
      supabase.from("fog_regions").select("*").eq("scene_id", scene.id),
      role === "OWNER" || role === "DM" ? supabase.from("monster_templates").select("*").eq("campaign_id", campaignId).order("name") : Promise.resolve({ data: [] }),
    ]);
    let monsterInstances: MonsterInstance[] = [];
    if (role === "OWNER" || role === "DM") {
      const { data } = await supabase.from("monster_instances").select("*,monster_templates(*)").eq("campaign_id", campaignId);
      monsterInstances = ((data ?? []) as Record<string, unknown>[]).map((r) => { const t = r.monster_templates as Record<string, unknown>; const template: MonsterTemplate = { id: String(t.id), campaignId: String(t.campaign_id), name: String(t.name), imageUrl: t.image_url ? String(t.image_url) : null, maxHp: Number(t.max_hp), ac: Number(t.ac), speed: Number(t.speed), abilities: t.abilities as MonsterTemplate["abilities"], notes: String(t.notes ?? ""), traits: t.traits as MonsterTemplate["traits"], actions: t.actions as MonsterTemplate["actions"], bonusActions: t.bonus_actions as MonsterTemplate["bonusActions"], reactions: t.reactions as MonsterTemplate["reactions"] }; return { id: String(r.id), campaignId, templateId: String(r.template_id), customName: String(r.custom_name), currentHp: Number(r.current_hp), maxHp: Number(r.max_hp), ac: Number(r.ac), conditions: (r.conditions as string[]) ?? [], visible: Boolean(r.visible), notes: String(r.notes ?? ""), dead: Boolean(r.dead), template }; });
    }
    let combat: CombatSession = { id: "none", campaignId, sceneId: scene.id, active: false, round: 1, currentIndex: 0, entries: [] };
    if (combatRow) { const { data: entries } = await supabase.from("initiative_entries").select("*").eq("combat_session_id", combatRow.id).order("sort_order"); combat = { id: combatRow.id, campaignId, sceneId: scene.id, active: true, round: combatRow.round, currentIndex: combatRow.current_index, entries: (entries ?? []).map((e) => ({ id: e.id, combatSessionId: e.combat_session_id, tokenId: e.token_id, monsterInstanceId: e.monster_instance_id, characterId: e.character_id, name: e.name, imageUrl: e.image_url, initiative: e.initiative, sortOrder: e.sort_order, groupKey: e.group_key, groupCount: e.group_count })) }; }
    const characters: Character[] = ((characterRows ?? []) as Record<string, unknown>[]).map((r) => ({ id: String(r.id), campaignId, ownerId: String(r.owner_id), name: String(r.name), imageUrl: r.image_url ? String(r.image_url) : null, imagePath: r.image_path ? String(r.image_path) : null, currentHp: Number(r.current_hp), maxHp: Number(r.max_hp), ac: Number(r.ac), speed: Number(r.speed), passivePerception: Number(r.passive_perception), passiveInvestigation: Number(r.passive_investigation), passiveInsight: Number(r.passive_insight), notes: String(r.notes ?? ""), conditions: (r.conditions as string[]) ?? [] }));
    const monsterTemplates: MonsterTemplate[] = ((templateRows ?? []) as Record<string, unknown>[]).map((r) => ({ id: String(r.id), campaignId, name: String(r.name), imageUrl: r.image_url ? String(r.image_url) : null, imagePath: r.image_path ? String(r.image_path) : null, maxHp: Number(r.max_hp), ac: Number(r.ac), speed: Number(r.speed), abilities: r.abilities as MonsterTemplate["abilities"], notes: String(r.notes ?? ""), traits: r.traits as MonsterTemplate["traits"], actions: r.actions as MonsterTemplate["actions"], bonusActions: r.bonus_actions as MonsterTemplate["bonusActions"], reactions: r.reactions as MonsterTemplate["reactions"] }));
    const overlays = await Promise.all(((overlayRows ?? []) as Record<string, unknown>[]).map(async (r) => { if (r.storage_path) { const { data: signed }=await supabase.storage.from("campaign-assets").createSignedUrl(String(r.storage_path),60*60*12); if(signed)r.image_url=signed.signedUrl; } return asOverlay(r); }));
    const tokens = await Promise.all(((tokenRows ?? []) as Record<string, unknown>[]).map(asToken).map(async (token) => {
      if (token.imagePath) return signTokenImage(token);
      if (token.imageUrl) return token;
      const characterImage = token.type === "PLAYER" ? characters.find((character) => character.id === token.referenceId)?.imageUrl : null;
      const monsterImage = token.type === "MONSTER" ? monsterInstances.find((monster) => monster.id === token.referenceId)?.template?.imageUrl : null;
      return signTokenImage({ ...token, imageUrl: characterImage ?? monsterImage ?? null });
    }));
    return { campaign: { id: campaign.id, name: campaign.name, joinCode: campaign.join_code, ownerId: campaign.owner_id, role, memberCount: 0, updatedAt: campaign.updated_at }, role, scene, overlays, tokens, characters, monsterTemplates, monsterInstances, combat, fogRegions: ((fogRows ?? []) as Record<string, unknown>[]).map((r) => ({ id: String(r.id), sceneId: String(r.scene_id), mode: r.mode as FogRegion["mode"], shape: r.shape as FogRegion["shape"], points: r.points as number[] })), selectedTokenId: null, activeFogTool: null, placement: null, previewPlayerView: false, shiftIntel: false, connected: true };
  },
  async moveToken(tokenId: string, x: number, y: number) { if (isSupabaseConfigured) { const { error } = await supabase.rpc("move_token", { p_token_id: tokenId, p_x: x, p_y: y }); if (error) throw error; } },
  async updateSceneGrid(sceneId: string, gridType: Scene["gridType"], gridSize: number) { if (isSupabaseConfigured) { const { error } = await supabase.from("scenes").update({ grid_type: gridType, grid_size: gridSize }).eq("id", sceneId); if (error) throw error; } },
  async placeCharacterToken(sceneId: string, characterId: string, x: number, y: number) { const { data, error } = await supabase.rpc("place_character_token", { p_scene_id: sceneId, p_character_id: characterId, p_x: x, p_y: y }); if (error) throw error; if (!data) throw new Error("Character placement returned no token."); return signTokenImage(asToken(data as Record<string, unknown>)); },
  async placeMonsterToken(sceneId: string, templateId: string, x: number, y: number) { const { data, error } = await supabase.rpc("place_monster_token", { p_scene_id: sceneId, p_template_id: templateId, p_x: x, p_y: y }); if (error) throw error; if (!data) throw new Error("Monster placement returned no token."); return signTokenImage(asToken(data as Record<string, unknown>)); },
  async updateToken(tokenId: string, patch: Partial<Pick<Token,"visible"|"rotation"|"size"|"locked"|"conditions"|"imageUrl">>) { if (isSupabaseConfigured) { const payload: Record<string, unknown> = {}; if (patch.visible !== undefined) payload.visible = patch.visible; if (patch.rotation !== undefined) payload.rotation = patch.rotation; if (patch.size !== undefined) payload.size = patch.size; if (patch.locked !== undefined) payload.locked = patch.locked; if (patch.conditions !== undefined) payload.conditions = patch.conditions; if (patch.imageUrl !== undefined) payload.image_url = patch.imageUrl; const { error } = await supabase.from("tokens").update(payload).eq("id", tokenId); if (error) throw error; } },
  async adjustMonsterHp(instanceId: string, amount: number, mode: "DAMAGE"|"HEAL") { if (isSupabaseConfigured) { const { error } = await supabase.rpc("adjust_monster_hp", { p_instance_id: instanceId, p_amount: amount, p_mode: mode }); if (error) throw error; } },
  async setMonsterHp(instanceId: string, currentHp: number, maxHp: number) { if (isSupabaseConfigured) { const { error } = await supabase.from("monster_instances").update({ current_hp: currentHp, max_hp: maxHp, dead: currentHp === 0 }).eq("id", instanceId); if (error) throw error; } },
  async updateOverlay(id: string, patch: Partial<SceneOverlay>) { if (isSupabaseConfigured) { const { error } = await supabase.from("scene_overlays").update({ x: patch.x, y: patch.y, width: patch.width, height: patch.height, rotation: patch.rotation, visible: patch.visible, locked: patch.locked, opacity: patch.opacity, z_index: patch.zIndex }).eq("id", id); if (error) throw error; } },
  async addOverlay(sceneId: string, campaignId: string, file: File): Promise<SceneOverlay> { const local: SceneOverlay = { id: crypto.randomUUID(), sceneId, name: file.name, imageUrl: URL.createObjectURL(file), kind: "EFFECT", x: 700, y: 450, width: 240, height: 180, rotation: 0, opacity: 1, zIndex: 5, visible: true, locked: false }; if (!isSupabaseConfigured) return local; const path = `${campaignId}/overlays/${local.id}-${file.name.replace(/[^a-z0-9.-]/gi,"-")}`; const { error: uploadError } = await supabase.storage.from("campaign-assets").upload(path, file); if (uploadError) throw uploadError; const { data: signed, error: signError } = await supabase.storage.from("campaign-assets").createSignedUrl(path, 60 * 60 * 12); if (signError) throw signError; const { data, error } = await supabase.from("scene_overlays").insert({ id: local.id, scene_id: sceneId, name: file.name, storage_path: path, image_url: signed.signedUrl, kind: "EFFECT", x: local.x, y: local.y, width: local.width, height: local.height, z_index: local.zIndex }).select("*").single(); if (error) throw error; return asOverlay(data as Record<string, unknown>); },
  async addFogRegion(region: FogRegion) { if (isSupabaseConfigured) { const { error } = await supabase.from("fog_regions").insert({ id: region.id, scene_id: region.sceneId, mode: region.mode, shape: region.shape, points: region.points }); if (error) throw error; } },
  async resetFog(sceneId: string, covered: boolean) { if (isSupabaseConfigured) { const { error } = await supabase.rpc("reset_scene_fog", { p_scene_id: sceneId, p_covered: covered }); if (error) throw error; } },
  async advanceTurn(combat: CombatSession, delta: 1|-1) { if (isSupabaseConfigured) { const { error } = await supabase.rpc("advance_turn", { p_combat_session_id: combat.id, p_delta: delta }); if (error) throw error; } },
};
