import type { AttackAnimationEvent, AttackPreset, CampaignRole, Character, CinematicEvent, CombatSession, DiceRoll, MonsterInstance, MonsterTemplate, NpcShopItem, NpcTemplate, Scene, SceneDiscoverable, SceneLink, SceneOverlay, TabletopState, Token, TokenInteraction, TokenMotionSegment, TokenPatrol } from "../domain/types";
import { isSupabaseConfigured, supabase } from "../lib/supabase";
import { createDemoState } from "../domain/demoData";

const asSceneLighting=(value:unknown):Scene["lighting"]=>value==="NIGHT"||value==="DARK"?"NIGHT":value==="MIDDAY"||value==="DIM"?"MIDDAY":"DAY";
const asScene = (r: Record<string, unknown>): Scene => ({ id: String(r.id), campaignId: String(r.campaign_id), mapId: r.map_id ? String(r.map_id) : null, name: String(r.name), mapUrl: r.map_url ? String(r.map_url) : null, width: Number(r.width), height: Number(r.height), gridType: r.grid_type as Scene["gridType"], gridSize: Number(r.grid_size), feetPerCell: Number(r.feet_per_cell), gridColor: String(r.grid_color), gridOpacity: Number(r.grid_opacity), gridLineWidth: Number(r.grid_line_width ?? 1), active: Boolean(r.active), revealed: Boolean(r.revealed), mapX: Number(r.map_x ?? 0), mapY: Number(r.map_y ?? 0), mapScale: Number(r.map_scale ?? 1), gridOffsetX: Number(r.grid_offset_x ?? 0), gridOffsetY: Number(r.grid_offset_y ?? 0), lighting: asSceneLighting(r.lighting), playerCameraX: r.player_camera_x === null || r.player_camera_x === undefined ? null : Number(r.player_camera_x), playerCameraY: r.player_camera_y === null || r.player_camera_y === undefined ? null : Number(r.player_camera_y), playerCameraZoom: Number(r.player_camera_zoom ?? 1) });
const asNpcTemplate = (r:Record<string,unknown>):NpcTemplate=>({id:String(r.id),name:String(r.name),imageUrl:r.image_url?String(r.image_url):null,imagePath:r.image_path?String(r.image_path):null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)});
const asToken = (r: Record<string, unknown>): Token => ({ id: String(r.id), sceneId: String(r.scene_id), referenceId: r.reference_id ? String(r.reference_id) : null, ownerUserId: r.owner_user_id ? String(r.owner_user_id) : null, type: r.type as Token["type"], displayName: String(r.display_name), imageUrl: r.image_url ? String(r.image_url) : null, imagePath: r.image_path ? String(r.image_path) : null, x: Number(r.x), y: Number(r.y), size: Number(r.size), rotation: Number(r.rotation), visible: Boolean(r.visible), locked: Boolean(r.locked), conditions: (r.conditions as string[] | null) ?? [] });
const asOverlay = (r: Record<string, unknown>): SceneOverlay => ({ id: String(r.id), sceneId: String(r.scene_id), name: String(r.name), imageUrl: String(r.image_url), kind: r.kind as SceneOverlay["kind"], x: Number(r.x), y: Number(r.y), width: Number(r.width), height: Number(r.height), rotation: Number(r.rotation), opacity: Number(r.opacity), zIndex: Number(r.z_index), visible: Boolean(r.visible), locked: Boolean(r.locked) });
const asSceneLink = (r: Record<string, unknown>): SceneLink => ({ id:String(r.id),sceneId:String(r.scene_id),destinationSceneId:String(r.destination_scene_id),label:String(r.label),x:Number(r.x),y:Number(r.y),musicMode:(r.music_mode??"KEEP") as SceneLink["musicMode"],musicTrackId:r.music_track_id?String(r.music_track_id):null,musicLoop:Boolean(r.music_loop??true),musicNextTrackId:r.music_next_track_id?String(r.music_next_track_id):null,musicNextLoop:Boolean(r.music_next_loop??true),ambienceMode:(r.ambience_mode??"KEEP") as SceneLink["ambienceMode"],ambienceTrackId:r.ambience_track_id?String(r.ambience_track_id):null,ambienceLoop:Boolean(r.ambience_loop??true) });
const asDiscoverable = (r: Record<string, unknown>): SceneDiscoverable => ({ id:String(r.id),campaignId:String(r.campaign_id),sceneId:String(r.scene_id),name:String(r.name),storagePath:r.storage_path?String(r.storage_path):null,imageUrl:r.image_url?String(r.image_url):null,x:Number(r.x),y:Number(r.y),hidden:Boolean(r.hidden),discoveredAt:r.discovered_at?String(r.discovered_at):null,discoveredBy:r.discovered_by?String(r.discovered_by):null,createdAt:String(r.created_at) });
const asPatrol = (r: Record<string, unknown>): TokenPatrol => ({ id:String(r.id),tokenId:String(r.token_id),sceneId:String(r.scene_id),mode:r.mode as TokenPatrol["mode"],active:Boolean(r.active),speed:Number(r.speed),waypointPauseMs:Number(r.waypoint_pause_ms),pauseDuringCombat:Boolean(r.pause_during_combat),currentWaypoint:Number(r.current_waypoint),direction:Number(r.direction) === -1 ? -1 : 1,waypoints:((r.waypoints as TokenPatrol["waypoints"]) ?? []).map((point,index)=>({id:point.id || `point-${index}`,x:Number(point.x),y:Number(point.y)})),createdAt:String(r.created_at),updatedAt:String(r.updated_at) });
const asMotionSegment=(r:Record<string,unknown>):TokenMotionSegment=>({tokenId:String(r.token_id),sceneId:String(r.scene_id),fromX:Number(r.from_x),fromY:Number(r.from_y),toX:Number(r.to_x),toY:Number(r.to_y),startedAt:String(r.started_at),durationMs:Number(r.duration_ms),revision:Number(r.revision),active:Boolean(r.active)});
const asShopItem=(r:Record<string,unknown>):NpcShopItem=>({id:String(r.id),interactionId:String(r.interaction_id),name:String(r.name),description:String(r.description??""),priceGp:Number(r.price_gp),quantity:r.quantity===null||r.quantity===undefined?null:Number(r.quantity),sortOrder:Number(r.sort_order)});
const asInteraction=(r:Record<string,unknown>):TokenInteraction=>{const legacy=String(r.dialogue_text??"");const rawPages=Array.isArray(r.dialogue_pages)?r.dialogue_pages:[];const dialoguePages=rawPages.map((page)=>String(page)).filter((page)=>page.trim().length>0);return {tokenId:String(r.token_id),campaignId:String(r.campaign_id),enabled:Boolean(r.enabled),type:r.type as TokenInteraction["type"],displayName:String(r.display_name??""),dialogueText:legacy,dialoguePages:dialoguePages.length?dialoguePages:(legacy.trim()?[legacy]:[]),shopItems:((r.npc_shop_items as Record<string,unknown>[]|null)??[]).map(asShopItem).sort((a,b)=>a.sortOrder-b.sortOrder)};};
const signTokenImage = async (token: Token) => { if (!token.imagePath) return token; const { data }=await supabase.storage.from("campaign-assets").createSignedUrl(token.imagePath,60*60*12); return data?.signedUrl?{...token,imageUrl:data.signedUrl}:token; };
const throwQueryError = (error: { message?: string } | null, fallback: string) => { if (error) throw new Error(error.message || fallback); };
let serverClockOffsetMs = 0;
let serverClockCalibratedAt = 0;
let serverClockCalibration: Promise<void> | null = null;
export const serverNowMs = () => Date.now() + serverClockOffsetMs;
export const PATROL_PRESENTATION_DELAY_MS = 180;
export const getServerClockOffsetMs = () => serverClockOffsetMs;
const ensureServerClock = async () => {
  if (!isSupabaseConfigured || Date.now() - serverClockCalibratedAt < 60_000) return;
  if (serverClockCalibration) return serverClockCalibration;
  serverClockCalibration = (async () => {
    const started = Date.now();
    const { data, error } = await supabase.rpc("wayfinder_server_now");
    const ended = Date.now();
    if (error) throw error;
    const raw = Array.isArray(data) ? data[0] : data;
    const serverTime = Date.parse(String(raw));
    if (!Number.isFinite(serverTime)) throw new Error("Invalid server clock response.");
    serverClockOffsetMs = serverTime - (started + ended) / 2;
    serverClockCalibratedAt = ended;
  })().finally(() => { serverClockCalibration = null; });
  return serverClockCalibration;
};
const publicCharacterFields = "id,campaign_id,owner_id,name,image_url,image_path,current_hp,max_hp,temp_hp,ac,speed,strength,dexterity,constitution,intelligence,wisdom,charisma,passive_perception,passive_investigation,passive_insight,conditions";
const asCharacter = (r: Record<string, unknown>): Character => ({ id: String(r.id), campaignId: String(r.campaign_id), ownerId: String(r.owner_id), name: String(r.name), imageUrl: r.image_url ? String(r.image_url) : null, imagePath: r.image_path ? String(r.image_path) : null, currentHp: Number(r.current_hp), maxHp: Number(r.max_hp), tempHp: Number(r.temp_hp ?? 0), ac: Number(r.ac), speed: Number(r.speed), abilities: { str: Number(r.strength ?? 10), dex: Number(r.dexterity ?? 10), con: Number(r.constitution ?? 10), int: Number(r.intelligence ?? 10), wis: Number(r.wisdom ?? 10), cha: Number(r.charisma ?? 10) }, passivePerception: Number(r.passive_perception), passiveInvestigation: Number(r.passive_investigation), passiveInsight: Number(r.passive_insight), notes: "", conditions: (r.conditions as string[]) ?? [] });
const asAttackEvent = (row: Record<string, unknown>): AttackAnimationEvent => ({ id: String(row.id), campaignId: String(row.campaign_id), attackerTokenId: String(row.attacker_token_id), targetTokenId: String(row.target_token_id), preset: row.preset as AttackPreset, createdAt: String(row.created_at) });
const asMonsterTemplate = (r: Record<string, unknown>): MonsterTemplate => ({ id:String(r.id),name:String(r.name),imageUrl:r.image_url?String(r.image_url):null,imagePath:r.image_path?String(r.image_path):null,creatureSize:String(r.creature_size ?? "Medium"),creatureType:String(r.creature_type ?? ""),maxHp:Number(r.max_hp),hpFormula:r.hp_formula?String(r.hp_formula):null,ac:Number(r.ac),speed:Number(r.speed),movement:(r.movement as MonsterTemplate["movement"]) ?? {walk:Number(r.speed),fly:0,swim:0,climb:0,burrow:0,hover:false},initiative:(r.initiative as MonsterTemplate["initiative"]) ?? {modifier:null,score:null},abilities:r.abilities as MonsterTemplate["abilities"],savingThrows:(r.saving_throws as MonsterTemplate["savingThrows"]) ?? {},skills:(r.skills as MonsterTemplate["skills"]) ?? {},damageVulnerabilities:(r.damage_vulnerabilities as string[]|null) ?? [],damageResistances:(r.damage_resistances as string[]|null) ?? [],damageImmunities:(r.damage_immunities as string[]|null) ?? [],conditionImmunities:(r.condition_immunities as string[]|null) ?? [],senses:(r.senses as MonsterTemplate["senses"]) ?? [],passivePerception:r.passive_perception===null||r.passive_perception===undefined?null:Number(r.passive_perception),languages:(r.languages as string[]|null) ?? [],notes:String(r.notes ?? ""),traits:(r.traits as MonsterTemplate["traits"]) ?? [],actions:(r.actions as MonsterTemplate["actions"]) ?? [],bonusActions:(r.bonus_actions as MonsterTemplate["bonusActions"]) ?? [],reactions:(r.reactions as MonsterTemplate["reactions"]) ?? [],legendaryActions:(r.legendary_actions as MonsterTemplate["legendaryActions"]) ?? [],legendaryActionUses:r.legendary_action_uses===null||r.legendary_action_uses===undefined?null:Number(r.legendary_action_uses),spellcasting:(r.spellcasting as MonsterTemplate["spellcasting"]) ?? [] });
export const asDiceRoll = (row: Record<string, unknown>): DiceRoll => {
  const profile = row.profiles as Record<string, unknown> | Record<string, unknown>[] | null;
  const displayName = Array.isArray(profile) ? profile[0]?.display_name : profile?.display_name;
  return { id: String(row.id), campaignId: String(row.campaign_id), rollerUserId: String(row.roller_user_id), rollerRole: row.roller_role as CampaignRole, rollerDisplayName: displayName ? String(displayName) : null, sides: Number(row.sides), quantity: Number(row.quantity), results: (row.results as number[]) ?? [], total: Number(row.total), createdAt: String(row.created_at) };
};
export const asCinematicEvent = (row: Record<string, unknown>): CinematicEvent => ({ id:String(row.id),campaignId:String(row.campaign_id),name:String(row.name),duration:Number(row.duration),steps:(row.steps as CinematicEvent["steps"]) ?? [],createdAt:String(row.created_at) });

export const tabletopService = {
  async load(campaignId: string, playerView = false, sceneId?: string): Promise<TabletopState> {
    if (!isSupabaseConfigured || campaignId === "demo") return createDemoState(playerView);
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError) throw userError;
    if (!user) throw new Error("Sign in is required to open this tabletop.");
    try { await ensureServerClock(); } catch (clockError) { console.warn("Unable to calibrate Wayfinder server clock", clockError); }
    const [{ data: membership, error: memberError }, { data: campaign, error: campaignError }, { data: sceneRow, error: sceneError }] = await Promise.all([
      // Members can read the campaign roster. Filter to the signed-in user's row
      // before calling single(), otherwise a second player makes this query plural.
      supabase.from("campaign_members").select("role").eq("campaign_id", campaignId).eq("user_id", user.id).maybeSingle(),
      supabase.from("campaigns").select("id,name,join_code,owner_id,updated_at").eq("id", campaignId).single(),
      sceneId && !playerView
        ? supabase.from("scenes").select("*").eq("campaign_id", campaignId).eq("id", sceneId).single()
        : supabase.from("scenes").select("*").eq("campaign_id", campaignId).eq("active", true).maybeSingle(),
    ]);
    if (memberError) throw memberError; if (!membership) throw new Error("You are not a member of this campaign."); if (campaignError) throw campaignError; if (sceneError) throw sceneError; if (!sceneRow) throw new Error(playerView?"The DM has hidden the current scene.":"No live scene is selected.");
    const role = membership.role as CampaignRole; const scene = asScene(sceneRow as Record<string, unknown>);
    if (scene.mapId) { const { data: map } = await supabase.from("maps").select("storage_path").eq("id",scene.mapId).single(); if (map?.storage_path) { const { data: signed } = await supabase.storage.from("campaign-assets").createSignedUrl(map.storage_path,60*60*12); if (signed) scene.mapUrl=signed.signedUrl; } }
    const [{ data: tokenRows, error: tokenError }, { data: overlayRows, error: overlayError }, { data: characterRows, error: characterError }, { data: combatRow, error: combatError }, { data: templateRows, error: templateError }, { data: diceRows, error: diceError }, { data: linkRows, error: linkError }, { data: sceneRows, error: scenesError }, {data: discoverableRows,error:discoverableError}, {data:treasureRows,error:treasureError}, {data:patrolRows,error:patrolError}, {data:motionRows,error:motionError}, {data:interactionRows,error:interactionError}, {data:dreadRow,error:dreadError}, {data:npcTemplateRows,error:npcTemplateError}] = await Promise.all([
      supabase.from("tokens").select("id,scene_id,reference_id,owner_user_id,type,display_name,image_url,image_path,x,y,size,rotation,visible,locked,conditions").eq("scene_id", scene.id),
      supabase.from("scene_overlays").select("*").eq("scene_id", scene.id).order("z_index"),
      supabase.from("characters").select(publicCharacterFields).eq("campaign_id", campaignId),
      supabase.from("combat_sessions").select("*").eq("scene_id", scene.id).eq("active", true).maybeSingle(),
      role === "OWNER" || role === "DM" ? supabase.from("monster_templates").select("*").order("name") : Promise.resolve({ data: [], error: null }),
      supabase.from("tabletop_dice_rolls").select("id,campaign_id,roller_user_id,roller_role,sides,quantity,results,total,created_at,profiles(display_name)").eq("campaign_id", campaignId).order("created_at", { ascending: false }).limit(12),
      role === "OWNER" || role === "DM" ? supabase.from("scene_links").select("id,scene_id,destination_scene_id,label,x,y,music_mode,music_track_id,music_loop,music_next_track_id,music_next_loop,ambience_mode,ambience_track_id,ambience_loop").eq("scene_id",scene.id).order("created_at") : Promise.resolve({ data: [], error: null }),
      role === "OWNER" || role === "DM" ? supabase.from("scenes").select("*").eq("campaign_id",campaignId).order("created_at") : Promise.resolve({ data: [], error: null }),
      supabase.from("scene_discoverables").select("id,campaign_id,scene_id,name,x,y,hidden,discovered_at,discovered_by,created_at").eq("scene_id",scene.id),
      supabase.from("scene_discoverables").select("id,campaign_id,scene_id,name,storage_path,x,y,hidden,discovered_at,discovered_by,created_at").eq("campaign_id",campaignId).not("discovered_at","is",null).order("discovered_at",{ascending:false}),
      role === "OWNER" || role === "DM" ? supabase.from("token_patrols").select("*").eq("scene_id",scene.id) : Promise.resolve({data:[],error:null}),
      supabase.from("token_motion_segments").select("*").eq("scene_id",scene.id).eq("active",true),
      supabase.from("token_interactions").select("token_id,campaign_id,enabled,type,display_name,dialogue_text,dialogue_pages,npc_shop_items(*)" ).eq("campaign_id",campaignId),
      supabase.from("tabletop_cinematic_events").select("id,campaign_id,name,duration,steps,created_at").eq("campaign_id",campaignId).in("name",["Dread","Dread off"]).order("created_at",{ascending:false}).limit(1).maybeSingle(),
      role === "OWNER" || role === "DM" ? supabase.from("npc_templates").select("*").order("name") : Promise.resolve({data:[],error:null}),
    ]);
    throwQueryError(tokenError, "Unable to load tabletop tokens."); throwQueryError(overlayError, "Unable to load tabletop overlays."); throwQueryError(characterError, "Unable to load campaign characters."); throwQueryError(combatError, "Unable to load tabletop combat."); throwQueryError(templateError, "Unable to load monster templates."); throwQueryError(diceError, "Unable to load tabletop dice rolls."); throwQueryError(linkError, "Unable to load scene links."); throwQueryError(scenesError, "Unable to load campaign scenes."); throwQueryError(discoverableError,"Unable to load scene discoverables."); throwQueryError(treasureError,"Unable to load party treasure."); throwQueryError(patrolError,"Unable to load token patrols."); throwQueryError(motionError,"Unable to load token motion."); throwQueryError(interactionError,"Unable to load NPC interactions."); throwQueryError(dreadError,"Unable to load Dread state."); throwQueryError(npcTemplateError,"Unable to load NPC templates.");
    let monsterInstances: MonsterInstance[] = [];
    if (role === "OWNER" || role === "DM") {
      const { data, error } = await supabase.from("monster_instances").select("*,monster_templates(*)").eq("campaign_id", campaignId); throwQueryError(error, "Unable to load placed monsters.");
      monsterInstances = ((data ?? []) as Record<string, unknown>[]).map((r) => { const t = r.monster_templates as Record<string, unknown>; const template = asMonsterTemplate(t); return { id: String(r.id), campaignId, templateId: String(r.template_id), customName: String(r.custom_name), currentHp: Number(r.current_hp), maxHp: Number(r.max_hp), ac: Number(r.ac), conditions: (r.conditions as string[]) ?? [], visible: Boolean(r.visible), notes: String(r.notes ?? ""), dead: Boolean(r.dead), template }; });
    }
    let combat: CombatSession = { id: "none", campaignId, sceneId: scene.id, active: false, round: 1, currentIndex: 0, entries: [] };
    if (combatRow) { const { data: entries, error } = await supabase.from("initiative_entries").select("*").eq("combat_session_id", combatRow.id).order("sort_order"); throwQueryError(error, "Unable to load initiative."); combat = { id: combatRow.id, campaignId, sceneId: scene.id, active: true, round: combatRow.round, currentIndex: combatRow.current_index, entries: (entries ?? []).map((e) => ({ id: e.id, combatSessionId: e.combat_session_id, tokenId: e.token_id, monsterInstanceId: e.monster_instance_id, characterId: e.character_id, name: e.name, imageUrl: e.image_url, initiative: e.initiative, sortOrder: e.sort_order, groupKey: e.group_key, groupCount: e.group_count })) }; }
    const characters: Character[] = ((characterRows ?? []) as Record<string, unknown>[]).map(asCharacter);
    const npcTemplates: NpcTemplate[] = await Promise.all(((npcTemplateRows ?? []) as Record<string,unknown>[]).map(asNpcTemplate).map(async(item)=>{if(!item.imagePath)return item;const {data}=await supabase.storage.from("campaign-assets").createSignedUrl(item.imagePath,60*60*12);return data?.signedUrl?{...item,imageUrl:data.signedUrl}:item;}));
    const monsterTemplates: MonsterTemplate[] = ((templateRows ?? []) as Record<string, unknown>[]).map(asMonsterTemplate);
    const overlays = await Promise.all(((overlayRows ?? []) as Record<string, unknown>[]).map(async (r) => { if (r.storage_path) { const { data: signed }=await supabase.storage.from("campaign-assets").createSignedUrl(String(r.storage_path),60*60*12); if(signed)r.image_url=signed.signedUrl; } return asOverlay(r); }));
    const tokens = await Promise.all(((tokenRows ?? []) as Record<string, unknown>[]).map(asToken).map(async (token) => {
      if (token.imagePath) return signTokenImage(token);
      if (token.imageUrl) return token;
      const characterImage = token.type === "PLAYER" ? characters.find((character) => character.id === token.referenceId)?.imageUrl : null;
      const monsterImage = token.type === "MONSTER" ? monsterInstances.find((monster) => monster.id === token.referenceId)?.template?.imageUrl : null;
      const npcImage = token.type === "NPC" ? npcTemplates.find((npc) => npc.id === token.referenceId)?.imageUrl : null;
      return { ...token, imageUrl: characterImage ?? monsterImage ?? npcImage ?? null };
    }));
    const signDiscoverable=async(item:SceneDiscoverable)=>{if(!item.storagePath)return item;const {data}=await supabase.storage.from("campaign-assets").createSignedUrl(item.storagePath,60*60*12);return data?.signedUrl?{...item,imageUrl:data.signedUrl}:item;};
    const treasure=await Promise.all(((treasureRows??[]) as Record<string,unknown>[]).map(asDiscoverable).map(signDiscoverable));
    return { campaign: { id: campaign.id, name: campaign.name, joinCode: campaign.join_code, ownerId: campaign.owner_id, role, memberCount: 0, updatedAt: campaign.updated_at }, role, scene, scenes: ((sceneRows ?? []) as Record<string, unknown>[]).map(asScene), sceneLinks: ((linkRows ?? []) as Record<string, unknown>[]).map(asSceneLink), discoverables:((discoverableRows??[]) as Record<string,unknown>[]).map(asDiscoverable),treasure,discoveryReveal:null, overlays, tokens, transientTokenIds:[],motionSegments:((motionRows??[]) as Record<string,unknown>[]).map(asMotionSegment),tokenInteractions:((interactionRows??[]) as Record<string,unknown>[]).map(asInteraction), patrols:((patrolRows??[]) as Record<string,unknown>[]).map(asPatrol),patrolEditTokenId:null, characters, npcTemplates, monsterTemplates, monsterInstances, combat, diceRolls: ((diceRows ?? []) as Record<string, unknown>[]).map(asDiceRoll), selectedTokenId: null, placement: null, attackSelection: null, attackEvent: null, cinematicEvent: null, dreadActive: dreadRow?.name === "Dread", previewPlayerView: false, shiftIntel: false, connected: true };
  },
  async moveToken(tokenId: string, x: number, y: number) { if (isSupabaseConfigured) { const { error } = await supabase.rpc("move_token", { p_token_id: tokenId, p_x: x, p_y: y }); if (error) throw error; } },
  async checkpointPatrol(patrol:TokenPatrol,x:number,y:number,currentWaypoint:number,direction:1|-1,active:boolean){if(!isSupabaseConfigured)return {...patrol,currentWaypoint,direction,active};const {data,error}=await supabase.rpc("checkpoint_token_patrol",{p_patrol_id:patrol.id,p_x:x,p_y:y,p_current_waypoint:currentWaypoint,p_direction:direction,p_active:active});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("Patrol checkpoint returned no patrol.");return asPatrol(row as Record<string,unknown>);},
  async startPatrolSegment(patrol:TokenPatrol,fromX:number,fromY:number,toX:number,toY:number){const duration=Math.max(1,Math.round(Math.hypot(toX-fromX,toY-fromY)/patrol.speed*1000));if(!isSupabaseConfigured)return {tokenId:patrol.tokenId,sceneId:patrol.sceneId,fromX,fromY,toX,toY,startedAt:new Date().toISOString(),durationMs:duration,revision:1,active:true} satisfies TokenMotionSegment;const {data,error}=await supabase.rpc("start_token_motion_segment",{p_patrol_id:patrol.id,p_from_x:fromX,p_from_y:fromY,p_to_x:toX,p_to_y:toY,p_duration_ms:duration});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("Patrol segment returned no motion row.");return asMotionSegment(row as Record<string,unknown>);},
  async ensurePatrolSegment(patrolId:string){if(!isSupabaseConfigured)throw new Error("Patrol segment driver requires Supabase.");const {data,error}=await supabase.rpc("ensure_token_patrol_segment",{p_patrol_id:patrolId});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("Patrol segment driver returned no motion row.");return asMotionSegment(row as Record<string,unknown>);},
  async completePatrolSegment(patrolId:string,expectedRevision:number){if(!isSupabaseConfigured)throw new Error("Patrol segment driver requires Supabase.");const {data,error}=await supabase.rpc("complete_token_patrol_segment",{p_patrol_id:patrolId,p_expected_revision:expectedRevision});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("Patrol segment completion returned no patrol.");return asPatrol(row as Record<string,unknown>);},
  async interactWithNpc(tokenId:string){const {data,error}=await supabase.rpc("interact_with_npc",{p_token_id:tokenId});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("NPC interaction returned no token.");return asToken(row as Record<string,unknown>);},
  async updateTokenInteraction(tokenId:string,campaignId:string,patch:Partial<Omit<TokenInteraction,"tokenId"|"campaignId"|"shopItems">>){const pages=patch.dialoguePages?.map((page)=>page.trim()).filter(Boolean);const {error}=await supabase.from("token_interactions").upsert({token_id:tokenId,campaign_id:campaignId,enabled:patch.enabled,type:patch.type,display_name:patch.displayName,dialogue_text:pages!==undefined?(pages[0]??""):patch.dialogueText,dialogue_pages:pages},{onConflict:"token_id"});if(error)throw error;},
  async replaceShopItems(tokenId:string,items:Omit<NpcShopItem,"id"|"interactionId">[]){const {error:deleteError}=await supabase.from("npc_shop_items").delete().eq("interaction_id",tokenId);if(deleteError)throw deleteError;if(!items.length)return;const {error}=await supabase.from("npc_shop_items").insert(items.map((item,index)=>({interaction_id:tokenId,name:item.name,description:item.description,price_gp:item.priceGp,quantity:item.quantity,sort_order:index})));if(error)throw error;},
  async createPatrol(tokenId:string,sceneId:string):Promise<TokenPatrol>{const local:TokenPatrol={id:crypto.randomUUID(),tokenId,sceneId,mode:"LOOP",active:false,speed:60,waypointPauseMs:600,pauseDuringCombat:true,currentWaypoint:0,direction:1,waypoints:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(!isSupabaseConfigured)return local;const {data,error}=await supabase.from("token_patrols").insert({id:local.id,token_id:tokenId,scene_id:sceneId}).select("*").single();if(error)throw error;return asPatrol(data as Record<string,unknown>);},
  async updatePatrol(id:string,patch:Partial<Omit<TokenPatrol,"id"|"tokenId"|"sceneId"|"createdAt"|"updatedAt">>){if(!isSupabaseConfigured)return;const payload:Record<string,unknown>={};if(patch.mode!==undefined)payload.mode=patch.mode;if(patch.active!==undefined)payload.active=patch.active;if(patch.speed!==undefined)payload.speed=patch.speed;if(patch.waypointPauseMs!==undefined)payload.waypoint_pause_ms=patch.waypointPauseMs;if(patch.pauseDuringCombat!==undefined)payload.pause_during_combat=patch.pauseDuringCombat;if(patch.currentWaypoint!==undefined)payload.current_waypoint=patch.currentWaypoint;if(patch.direction!==undefined)payload.direction=patch.direction;if(patch.waypoints!==undefined)payload.waypoints=patch.waypoints;const {error}=await supabase.from("token_patrols").update(payload).eq("id",id);if(error)throw error;},
  async deletePatrol(id:string){if(!isSupabaseConfigured)return;const {error}=await supabase.from("token_patrols").delete().eq("id",id);if(error)throw error;},
  async updateSceneGrid(sceneId: string, gridType: Scene["gridType"], gridSize: number) { if (isSupabaseConfigured) { const { error } = await supabase.from("scenes").update({ grid_type: gridType, grid_size: gridSize }).eq("id", sceneId); if (error) throw error; } },
  async updateScene(sceneId: string, patch: Partial<Scene>) { if (!isSupabaseConfigured) return; const payload: Record<string, unknown> = {}; if (patch.gridType !== undefined) payload.grid_type=patch.gridType; if (patch.gridSize !== undefined) payload.grid_size=patch.gridSize; if (patch.feetPerCell !== undefined) payload.feet_per_cell=patch.feetPerCell; if (patch.gridColor !== undefined) payload.grid_color=patch.gridColor; if (patch.gridOpacity !== undefined) payload.grid_opacity=patch.gridOpacity; if (patch.gridLineWidth !== undefined) payload.grid_line_width=patch.gridLineWidth; if (patch.mapX !== undefined) payload.map_x=patch.mapX; if (patch.mapY !== undefined) payload.map_y=patch.mapY; if (patch.mapScale !== undefined) payload.map_scale=patch.mapScale; if (patch.gridOffsetX !== undefined) payload.grid_offset_x=patch.gridOffsetX; if (patch.gridOffsetY !== undefined) payload.grid_offset_y=patch.gridOffsetY; if (patch.lighting !== undefined) payload.lighting=patch.lighting; if (patch.playerCameraX !== undefined) payload.player_camera_x=patch.playerCameraX; if (patch.playerCameraY !== undefined) payload.player_camera_y=patch.playerCameraY; if (patch.playerCameraZoom !== undefined) payload.player_camera_zoom=patch.playerCameraZoom; const { error } = await supabase.from("scenes").update(payload).eq("id", sceneId); if (error) throw error; },
  async activateAndRevealScene(sceneId: string) { if (!isSupabaseConfigured) return; const {error}=await supabase.rpc("activate_and_reveal_scene",{p_scene_id:sceneId}); if(error)throw error; },
  async activateSceneLink(linkId: string) { if (!isSupabaseConfigured) return; const {error}=await supabase.rpc("activate_scene_link",{p_link_id:linkId}); if(error)throw error; },
  async addSceneLink(sceneId: string, destinationSceneId: string, label: string, x: number, y: number): Promise<SceneLink> { const local:SceneLink={id:crypto.randomUUID(),sceneId,destinationSceneId,label,x,y,musicMode:"KEEP",musicTrackId:null,musicLoop:true,musicNextTrackId:null,musicNextLoop:true,ambienceMode:"KEEP",ambienceTrackId:null,ambienceLoop:true}; if(!isSupabaseConfigured)return local; const {data,error}=await supabase.from("scene_links").insert({id:local.id,scene_id:sceneId,destination_scene_id:destinationSceneId,label,x,y}).select("id,scene_id,destination_scene_id,label,x,y,music_mode,music_track_id,music_loop,music_next_track_id,music_next_loop,ambience_mode,ambience_track_id,ambience_loop").single(); if(error)throw error; return asSceneLink(data as Record<string,unknown>); },
  async updateSceneLink(id: string, patch: Partial<Pick<SceneLink,"destinationSceneId"|"label"|"x"|"y"|"musicMode"|"musicTrackId"|"musicLoop"|"musicNextTrackId"|"musicNextLoop"|"ambienceMode"|"ambienceTrackId"|"ambienceLoop">>) { if(!isSupabaseConfigured)return; const payload:Record<string,unknown>={}; if(patch.destinationSceneId!==undefined)payload.destination_scene_id=patch.destinationSceneId; if(patch.label!==undefined)payload.label=patch.label; if(patch.x!==undefined)payload.x=patch.x; if(patch.y!==undefined)payload.y=patch.y; if(patch.musicMode!==undefined)payload.music_mode=patch.musicMode; if(patch.musicTrackId!==undefined)payload.music_track_id=patch.musicTrackId; if(patch.musicLoop!==undefined)payload.music_loop=patch.musicLoop; if(patch.musicNextTrackId!==undefined)payload.music_next_track_id=patch.musicNextTrackId; if(patch.musicNextLoop!==undefined)payload.music_next_loop=patch.musicNextLoop; if(patch.ambienceMode!==undefined)payload.ambience_mode=patch.ambienceMode; if(patch.ambienceTrackId!==undefined)payload.ambience_track_id=patch.ambienceTrackId; if(patch.ambienceLoop!==undefined)payload.ambience_loop=patch.ambienceLoop; const {error}=await supabase.from("scene_links").update(payload).eq("id",id); if(error)throw error; },
  async deleteSceneLink(id: string) { if(!isSupabaseConfigured)return; const {error}=await supabase.from("scene_links").delete().eq("id",id); if(error)throw error; },
  async placeCharacterToken(sceneId: string, characterId: string, x: number, y: number) { const { data, error } = await supabase.rpc("place_character_token", { p_scene_id: sceneId, p_character_id: characterId, p_x: x, p_y: y }); if (error) throw error; if (!data) throw new Error("Character placement returned no token."); return signTokenImage(asToken(data as Record<string, unknown>)); },
  async placeMonsterToken(sceneId: string, templateId: string, x: number, y: number) { const { data, error } = await supabase.rpc("place_monster_token", { p_scene_id: sceneId, p_template_id: templateId, p_x: x, p_y: y }); if (error) throw error; if (!data) throw new Error("Monster placement returned no token."); return signTokenImage(asToken(data as Record<string, unknown>)); },
  async placeNpcToken(sceneId:string,templateId:string,x:number,y:number){const {data,error}=await supabase.rpc("place_npc_token",{p_scene_id:sceneId,p_template_id:templateId,p_x:x,p_y:y});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("NPC placement returned no token.");return signTokenImage(asToken(row as Record<string,unknown>));},
  async updateToken(tokenId: string, patch: Partial<Pick<Token,"visible"|"rotation"|"size"|"locked"|"conditions"|"imageUrl">>) {
    if (!isSupabaseConfigured) return;
    const payload: Record<string, unknown> = {};
    if (patch.visible !== undefined) payload.visible = patch.visible;
    if (patch.rotation !== undefined) payload.rotation = patch.rotation;
    if (patch.locked !== undefined) payload.locked = patch.locked;
    if (patch.conditions !== undefined) payload.conditions = patch.conditions;
    if (patch.imageUrl !== undefined) payload.image_url = patch.imageUrl;
    if (Object.keys(payload).length) {
      const { error } = await supabase.from("tokens").update(payload).eq("id", tokenId);
      if (error) throw error;
    }
    if (patch.size !== undefined) {
      const { error } = await supabase.rpc("set_token_size_and_default", {
        p_token_id: tokenId,
        p_size: patch.size,
      });
      if (error) throw error;
    }
  },
  async adjustMonsterHp(instanceId: string, amount: number, mode: "DAMAGE"|"HEAL") { if (isSupabaseConfigured) { const { error } = await supabase.rpc("adjust_monster_hp", { p_instance_id: instanceId, p_amount: amount, p_mode: mode }); if (error) throw error; } },
  async setMonsterHp(instanceId: string, currentHp: number, maxHp: number) { if (isSupabaseConfigured) { const { error } = await supabase.from("monster_instances").update({ current_hp: currentHp, max_hp: maxHp, dead: currentHp === 0 }).eq("id", instanceId); if (error) throw error; } },
  async adjustCharacterHp(characterId: string, amount: number, mode: "DAMAGE"|"HEAL") { const { data, error } = await supabase.rpc("adjust_character_hp", { p_character_id: characterId, p_amount: amount, p_mode: mode }); if (error) throw error; if (!data) throw new Error("Character HP adjustment returned no character."); return asCharacter(data as Record<string, unknown>); },
  async setCharacterCombat(characterId: string, currentHp: number, maxHp: number, tempHp: number, ac: number) { const { data, error } = await supabase.rpc("set_character_combat", { p_character_id: characterId, p_current_hp: currentHp, p_max_hp: maxHp, p_temp_hp: tempHp, p_ac: ac }); if (error) throw error; if (!data) throw new Error("Character combat update returned no character."); return asCharacter(data as Record<string, unknown>); },
  async setCharacterAbilities(characterId: string, abilities: Character["abilities"]) { const { data, error } = await supabase.rpc("set_character_abilities", { p_character_id: characterId, p_strength: abilities.str, p_dexterity: abilities.dex, p_constitution: abilities.con, p_intelligence: abilities.int, p_wisdom: abilities.wis, p_charisma: abilities.cha }); if (error) throw error; if (!data) throw new Error("Character ability update returned no character."); return asCharacter(data as Record<string, unknown>); },
  async updateOverlay(id: string, patch: Partial<SceneOverlay>) { if (isSupabaseConfigured) { const { error } = await supabase.from("scene_overlays").update({ x: patch.x, y: patch.y, width: patch.width, height: patch.height, rotation: patch.rotation, visible: patch.visible, locked: patch.locked, opacity: patch.opacity, z_index: patch.zIndex }).eq("id", id); if (error) throw error; } },
  async deleteOverlay(id: string) {
    if (!isSupabaseConfigured) return;
    const { data: overlay, error: loadError } = await supabase.from("scene_overlays").select("storage_path").eq("id", id).single();
    if (loadError) throw loadError;
    const { error: deleteError } = await supabase.from("scene_overlays").delete().eq("id", id);
    if (deleteError) throw deleteError;
    const storagePath = overlay?.storage_path ? String(overlay.storage_path) : null;
    if (storagePath) {
      const { error: assetError } = await supabase.storage.from("campaign-assets").remove([storagePath]);
      if (assetError) throw assetError;
    }
  },
  async createNpcTemplate(campaignId:string,name:string,file:File):Promise<NpcTemplate>{const id=crypto.randomUUID();const path=`${campaignId}/npc-templates/${id}-${file.name.replace(/[^a-z0-9.-]/gi,"-")}`;const {error:uploadError}=await supabase.storage.from("campaign-assets").upload(path,file);if(uploadError)throw uploadError;const {data:signed,error:signError}=await supabase.storage.from("campaign-assets").createSignedUrl(path,60*60*12);if(signError)throw signError;const {data,error}=await supabase.from("npc_templates").insert({id,name,image_path:path,image_url:null}).select("*").single();if(error){void supabase.storage.from("campaign-assets").remove([path]);throw error;}const item=asNpcTemplate(data as Record<string,unknown>);return {...item,imageUrl:signed.signedUrl};},
  async deleteNpcTemplate(id:string){const {data,error}=await supabase.from("npc_templates").select("image_path").eq("id",id).single();if(error)throw error;const {error:deleteError}=await supabase.from("npc_templates").delete().eq("id",id);if(deleteError)throw deleteError;if(data?.image_path){const {error:assetError}=await supabase.storage.from("campaign-assets").remove([String(data.image_path)]);if(assetError)throw assetError;}},
  async addOverlay(sceneId: string, campaignId: string, file: File): Promise<SceneOverlay> { const local: SceneOverlay = { id: crypto.randomUUID(), sceneId, name: file.name, imageUrl: URL.createObjectURL(file), kind: "EFFECT", x: 700, y: 450, width: 240, height: 180, rotation: 0, opacity: 1, zIndex: 5, visible: true, locked: false }; if (!isSupabaseConfigured) return local; const path = `${campaignId}/overlays/${local.id}-${file.name.replace(/[^a-z0-9.-]/gi,"-")}`; const { error: uploadError } = await supabase.storage.from("campaign-assets").upload(path, file); if (uploadError) throw uploadError; const { data: signed, error: signError } = await supabase.storage.from("campaign-assets").createSignedUrl(path, 60 * 60 * 12); if (signError) throw signError; const { data, error } = await supabase.from("scene_overlays").insert({ id: local.id, scene_id: sceneId, name: file.name, storage_path: path, image_url: signed.signedUrl, kind: "EFFECT", x: local.x, y: local.y, width: local.width, height: local.height, z_index: local.zIndex }).select("*").single(); if (error) throw error; return asOverlay(data as Record<string, unknown>); },
  async addDiscoverable(sceneId:string,campaignId:string,name:string,file:File,hidden:boolean):Promise<SceneDiscoverable>{const id=crypto.randomUUID();const local:SceneDiscoverable={id,campaignId,sceneId,name,storagePath:null,imageUrl:URL.createObjectURL(file),x:700,y:450,hidden,discoveredAt:null,discoveredBy:null,createdAt:new Date().toISOString()};if(!isSupabaseConfigured)return local;const path=`${campaignId}/discoverables/${id}-${file.name.replace(/[^a-z0-9.-]/gi,"-")}`;const {error:uploadError}=await supabase.storage.from("campaign-assets").upload(path,file);if(uploadError)throw uploadError;const {data,error}=await supabase.from("scene_discoverables").insert({id,campaign_id:campaignId,scene_id:sceneId,name,storage_path:path,x:local.x,y:local.y,hidden}).select("*").single();if(error)throw error;return asDiscoverable(data as Record<string,unknown>);},
  async updateDiscoverable(id:string,patch:Partial<Pick<SceneDiscoverable,"name"|"x"|"y"|"hidden">>){const {error}=await supabase.from("scene_discoverables").update({name:patch.name,x:patch.x,y:patch.y,hidden:patch.hidden}).eq("id",id);if(error)throw error;},
  async deleteDiscoverable(id:string){const {data,error}=await supabase.from("scene_discoverables").select("storage_path").eq("id",id).single();if(error)throw error;const {error:deleteError}=await supabase.from("scene_discoverables").delete().eq("id",id);if(deleteError)throw deleteError;if(data.storage_path){const {error:assetError}=await supabase.storage.from("campaign-assets").remove([data.storage_path]);if(assetError)throw assetError;}},
  async discover(id:string){const {data,error}=await supabase.rpc("discover_scene_discoverable",{p_discoverable_id:id});if(error)throw error;const item=asDiscoverable(data as Record<string,unknown>);if(!item.storagePath)return item;const {data:signed}=await supabase.storage.from("campaign-assets").createSignedUrl(item.storagePath,60*60*12);return signed?.signedUrl?{...item,imageUrl:signed.signedUrl}:item;},
  async triggerAttack(campaignId: string, attackerTokenId: string, targetTokenId: string, preset: AttackPreset): Promise<AttackAnimationEvent> { const local: AttackAnimationEvent = { id: crypto.randomUUID(), campaignId, attackerTokenId, targetTokenId, preset, createdAt: new Date().toISOString() }; if (!isSupabaseConfigured) return local; const { data, error } = await supabase.from("tabletop_animation_events").insert({ campaign_id: campaignId, attacker_token_id: attackerTokenId, target_token_id: targetTokenId, preset }).select("id,campaign_id,attacker_token_id,target_token_id,preset,created_at").single(); if (error) throw error; return asAttackEvent(data as Record<string, unknown>); },
  async triggerCinematic(campaignId: string,name: string,duration: number,steps: CinematicEvent["steps"]): Promise<CinematicEvent> { const local={id:crypto.randomUUID(),campaignId,name,duration,steps,createdAt:new Date().toISOString()};if(!isSupabaseConfigured)return local;const {data,error}=await supabase.from("tabletop_cinematic_events").insert({campaign_id:campaignId,name,duration,steps}).select("id,campaign_id,name,duration,steps,created_at").single();if(error)throw error;return asCinematicEvent(data as Record<string,unknown>); },
  async resetDreadOnTableLaunch(campaignId: string) {
    if (!isSupabaseConfigured) return;
    const { data, error } = await supabase
      .from("tabletop_cinematic_events")
      .select("name")
      .eq("campaign_id", campaignId)
      .in("name", ["Dread", "Dread off"])
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (error) throw error;
    if (data?.name === "Dread") {
      await this.triggerCinematic(campaignId, "Dread off", 100, []);
    }
  },
  async hydrateDiceRollerName(roll: DiceRoll): Promise<DiceRoll> {
    if (roll.rollerRole !== "PLAYER" || roll.rollerDisplayName) return roll;
    const { data, error } = await supabase.from("profiles").select("display_name").eq("id", roll.rollerUserId).maybeSingle();
    if (error) throw error;
    return { ...roll, rollerDisplayName: data?.display_name ? String(data.display_name) : null };
  },
  async rollDice(campaignId: string, sides: number, quantity: number): Promise<DiceRoll> { const { data, error } = await supabase.rpc("roll_tabletop_dice", { p_campaign_id: campaignId, p_sides: sides, p_quantity: quantity }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; if (!row) throw new Error("Dice roll returned no result."); return tabletopService.hydrateDiceRollerName(asDiceRoll(row as Record<string, unknown>)); },
  async advanceTurn(combat: CombatSession, delta: 1|-1) { if (isSupabaseConfigured) { const { error } = await supabase.rpc("advance_turn", { p_combat_session_id: combat.id, p_delta: delta }); if (error) throw error; } },
};
