import { ArrowRight, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";

export function AuthPage({ register=false }: { register?: boolean }) {
  const {signIn,signInWithGoogle,signUp,configured}=useAuth(); const navigate=useNavigate(); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const message=register?await signUp(String(f.get("email")),String(f.get("password")),String(f.get("name"))):await signIn(String(f.get("email")),String(f.get("password")));setBusy(false);if(message)setError(message);else navigate("/dashboard");}
  async function googleSignIn(){setBusy(true);setError(null);try{const message=await signInWithGoogle();if(message)setError(message);}catch{setError("Google sign-in could not start. Please try again.");}finally{setBusy(false);}}
  return <main className="auth-page"><section className="auth-story"><div className="auth-logo">W</div><p className="eyebrow">REALTIME VIRTUAL TABLETOP</p><h1>Run the encounter.<br/><em>Stay in the story.</em></h1><p>One focused surface for maps, creatures, fog, initiative, and the decisions that keep a session moving.</p><ul><li><ShieldCheck/>Role-aware player and DM data</li><li><ShieldCheck/>Image scenes with layered props and effects</li><li><ShieldCheck/>Realtime movement and combat state</li></ul></section><section className="auth-card"><p className="eyebrow">{register?"CREATE YOUR ACCOUNT":"WELCOME BACK"}</p><h2>{register?"Begin a new chronicle":"Return to the table"}</h2><p>{register?"Build your campaign command center.":"Your campaigns are waiting."}</p>{!configured&&<p className="auth-config-warning">Supabase authentication needs to be configured before anyone can sign in.</p>}<button className="oauth-button" type="button" disabled={busy} onClick={()=>void googleSignIn()}><span aria-hidden="true">G</span>Continue with Google</button><div className="auth-divider"><span>or continue with email</span></div><form onSubmit={submit}>{register&&<label>Display name<div><ShieldCheck/><input name="name" required placeholder="Morgan"/></div></label>}<label>Email<div><Mail/><input name="email" type="email" required placeholder="keeper@example.com"/></div></label><label>Password<div><LockKeyhole/><input name="password" type="password" minLength={8} required placeholder="At least 8 characters"/></div></label>{error&&<p className="form-error">{error}</p>}<button className="primary-action" disabled={busy}>{busy?"Please wait…":register?"Create account":"Enter Wayfinder"}<ArrowRight/></button></form><p className="auth-switch">{register?"Already have an account? ":"New to Wayfinder? "}<Link to={register?"/login":"/register"}>{register?"Sign in":"Create account"}</Link></p></section></main>;
}
