import { ArrowLeft, BookOpen, Copy, FileImage, Map, NotebookPen, Plus, Settings, Shield, Skull, Swords, Upload, Users } from "lucide-react";
import { useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AppShell } from "../components/AppShell";
import { demoCampaign } from "../domain/demoData";
import { isSupabaseConfigured, supabase } from "../lib/supabase";

const sections=[{id:"players",label:"Players",icon:Users},{id:"characters",label:"Characters",icon:Shield},{id:"maps",label:"Maps & scenes",icon:Map},{id:"monsters",label:"Monsters",icon:Skull},{id:"encounters",label:"Encounters",icon:Swords},{id:"notes",label:"Notes",icon:NotebookPen},{id:"settings",label:"Settings",icon:Settings}];
export function CampaignPage(){const {campaignId="demo"}=useParams();const navigate=useNavigate();const [tab,setTab]=useState("maps");const [notice,setNotice]=useState<string|null>(null);const mapInput=useRef<HTMLInputElement>(null);async function uploadMap(file?:File){if(!file)return;setNotice("Preparing scene…");try{if(isSupabaseConfigured&&campaignId!=="demo"){const id=crypto.randomUUID();const path=`${campaignId}/maps/${id}-${file.name.replace(/[^a-z0-9.-]/gi,"-")}`;const {error:u}=await supabase.storage.from("campaign-assets").upload(path,file);if(u)throw u;const {data:map,error:m}=await supabase.from("maps").insert({campaign_id:campaignId,name:file.name,storage_path:path,width:1600,height:1000}).select("id").single();if(m)throw m;const {error:inactive}=await supabase.from("scenes").update({active:false}).eq("campaign_id",campaignId).eq("active",true);if(inactive)throw inactive;const {error:sceneError}=await supabase.from("scenes").insert({campaign_id:campaignId,map_id:map.id,name:file.name.replace(/\.[^.]+$/,""),width:1600,height:1000,active:true});if(sceneError)throw sceneError;}setNotice(`${file.name} is ready as an image-backed scene.`);}catch(e){setNotice(e instanceof Error?e.message:"Upload failed");}}
return <AppShell><main className="campaign-page"><aside className="campaign-nav"><Link to="/dashboard" className="back-link"><ArrowLeft/>All campaigns</Link><div className="campaign-identity"><span>{demoCampaign.name[0]}</span><div><small>CAMPAIGN</small><h2>{demoCampaign.name}</h2></div></div><nav>{sections.map(s=><button key={s.id} className={tab===s.id?"active":""} onClick={()=>setTab(s.id)}><s.icon/>{s.label}</button>)}</nav><div className="campaign-code"><small>PLAYER JOIN CODE</small><div><b>{demoCampaign.joinCode}</b><button onClick={()=>void navigator.clipboard.writeText(demoCampaign.joinCode)}><Copy/></button></div></div></aside><section className="campaign-content"><header><div><p className="eyebrow">CAMPAIGN SETUP</p><h1>{sections.find(s=>s.id===tab)?.label}</h1><p>Configure the world here so the live table stays focused.</p></div><button className="launch-table" onClick={()=>navigate(`/campaign/${campaignId}/dm`)}><Swords/><span><small>OWNER · GAME MASTER</small>LAUNCH TABLE</span></button></header>{notice&&<div className="notice">{notice}</div>}<CampaignSection tab={tab} onUpload={()=>mapInput.current?.click()} campaignId={campaignId}/><input ref={mapInput} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void uploadMap(e.target.files?.[0])}/></section></main></AppShell>}

function CampaignSection({tab,onUpload,campaignId}:{tab:string;onUpload():void;campaignId:string}){
if(tab==="maps")return <div className="setup-layout"><section className="setup-main"><div className="setup-heading"><div><p className="eyebrow">IMAGE-BACKED SCENES</p><h2>Ruined Library — Lower Hall</h2></div><button className="secondary-action" onClick={onUpload}><Upload/>Upload map image</button></div><div className="scene-preview"><div className="scene-preview-map"><span><FileImage/><b>Base map image</b><small>1600 × 1000 · Square grid · 5 ft</small></span></div><div className="scene-facts"><span><small>GRID</small><b>80 px</b></span><span><small>FOG</small><b>Enabled</b></span><span><small>OVERLAYS</small><b>1 asset</b></span><span><small>STATUS</small><b className="online">Active</b></span></div></div><div className="asset-note"><LayersIllustration/><div><h3>Layer props and effects during play</h3><p>Upload transparent fires, traps, furniture, spell effects, or other image assets in the tabletop. Each overlay can be moved, resized, rotated, hidden, reordered, or locked independently of the base map.</p></div></div></section><aside className="setup-side"><p className="eyebrow">SCENES</p><button className="scene-row active"><span>RL</span><div><b>Ruined Library</b><small>Active · 4 tokens</small></div></button><button className="scene-row"><span>GC</span><div><b>Gate Courtyard</b><small>Draft · No map</small></div></button><button className="add-row"><Plus/>Create scene</button></aside></div>;
if(tab==="monsters")return <div className="library-layout"><div className="library-intro"><p className="eyebrow">ORIGINAL CREATURE LIBRARY</p><h2>Reusable templates, independent instances</h2><p>Templates hold reusable rules. Every placed creature gets its own HP, conditions, visibility, and encounter notes.</p><button className="primary-action compact"><Plus/>New template</button></div>{["Cave Scout","Animated Guardian","Lantern Wisp"].map((name,i)=><article className="monster-card" key={name}><span>{name[0]}</span><div><small>{i===0?"SMALL HUMANOID":"MEDIUM CONSTRUCT"}</small><h3>{name}</h3><p>AC {15+i} · {7+i*11} HP · 30 ft</p></div><button><BookOpen/></button></article>)}</div>;
if(tab==="encounters")return <div className="encounter-setup"><div><p className="eyebrow">PREPARED ENCOUNTER</p><h2>Ruined Library Ambush</h2><p>3 Cave Scouts · 1 Animated Guardian</p></div><div className="encounter-stack"><span>CS ×3</span><span>AG ×1</span><button><Plus/>Add creatures</button></div><button className="secondary-action">Load into active scene</button></div>;
if(tab==="players")return <div className="member-table">{[["Morgan","OWNER · DM"],["Avery","PLAYER"],["Rowan","PLAYER"],["Sam","SPECTATOR"]].map(([n,r])=><div key={n}><span>{n[0]}</span><b>{n}</b><small>{r}</small><button>Manage</button></div>)}</div>;
if(tab==="characters")return <div className="empty-setup"><Shield/><h2>Fast-reference characters</h2><p>Character records keep the combat values a game master checks most often.</p><button className="primary-action compact"><Plus/>Add character</button></div>;
if(tab==="notes")return <div className="notes-editor"><input defaultValue="Session 08 — Beneath the Archive"/><textarea defaultValue="The brass key carried by the scout opens the sealed lift. The Lantern Wisp recognizes Elowen."/><small>Campaign notes are DM-only and never sent to player clients.</small></div>;
return <div className="empty-setup"><Settings/><h2>Campaign settings</h2><p>Rename the campaign, manage permissions, and archive the chronicle.</p><Link to={`/campaign/${campaignId}/play`} className="secondary-action">Preview player launch</Link></div>}
function LayersIllustration(){return <div className="layers-illustration"><i/><i/><i/></div>}
