import { ArrowRight, CalendarDays, Copy, Plus, Swords, UserPlus, Users } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { AppShell } from "../components/AppShell";
import type { Campaign } from "../domain/types";
import { campaignService } from "../services/campaignService";

const errorMessage = (error: unknown, fallback: string) => {
  if (error instanceof Error) return error.message;
  if (import.meta.env.DEV && error && typeof error === "object" && "message" in error && typeof error.message === "string") return error.message;
  return fallback;
};

export function DashboardPage(){const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [mode,setMode]=useState<"create"|"join"|null>(null);const [error,setError]=useState<string|null>(null);const navigate=useNavigate();useEffect(()=>{void campaignService.list().then(setCampaigns).catch(e=>setError(errorMessage(e,"Unable to load campaigns.")));},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError(null);const f=new FormData(e.currentTarget);try{if(mode==="create"){const campaign=await campaignService.create(String(f.get("name")));navigate(`/campaign/${campaign.id}`);}else{const id=await campaignService.join(String(f.get("code")));navigate(`/campaign/${id}`);}}catch(e){setError(errorMessage(e,"Unable to continue"));}}
return <AppShell><main className="dashboard"><div className="dashboard-title"><div><p className="eyebrow">YOUR CHRONICLES</p><h1>Campaigns</h1><p>Prepare away from the table. Launch when the story begins.</p></div><div><button className="secondary-action" onClick={()=>setMode("join")}><UserPlus/>Join campaign</button><button className="primary-action compact" onClick={()=>setMode("create")}><Plus/>New campaign</button></div></div>{error&&<p className="form-error">{error}</p>}<section className="campaign-grid">{campaigns.map(c=><article className="campaign-card" key={c.id}><div className="campaign-cover"><span>{c.name.slice(0,1)}</span><em>{c.role}</em></div><div className="campaign-card-body"><p className="eyebrow">ACTIVE CAMPAIGN</p><h2>{c.name}</h2><div className="campaign-meta"><span><Users/>{c.memberCount||5} members</span><span><CalendarDays/>Updated today</span></div><div className="join-code"><small>JOIN CODE</small><b>{c.joinCode}</b><button onClick={()=>void navigator.clipboard.writeText(c.joinCode)} aria-label="Copy join code"><Copy/></button></div><button className="launch-card" onClick={()=>navigate(`/campaign/${c.id}`)}>Open campaign <ArrowRight/></button></div></article>)}<button className="new-campaign-card" onClick={()=>setMode("create")}><Plus/><b>Create a campaign</b><span>Start a new world and invite your table.</span></button></section>{mode&&<div className="inline-drawer"><div><p className="eyebrow">{mode==="create"?"NEW CHRONICLE":"JOIN A TABLE"}</p><h2>{mode==="create"?"Name your campaign":"Enter a join code"}</h2></div><form onSubmit={submit}><input name={mode==="create"?"name":"code"} placeholder={mode==="create"?"The Ashen Crown":"RUNE-72"} required/><button className="primary-action compact">{mode==="create"?<Plus/>:<Swords/>}{mode==="create"?"Create":"Join"}</button><button type="button" className="text-action" onClick={()=>setMode(null)}>Cancel</button></form></div>}</main></AppShell>}
