import { ArrowLeft, Eye, EyeOff, Grid3X3, Layers3, Link2, Pause, Play, Route, Sun, Trash2, Upload, Users } from "lucide-react";
import { useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { TabletopProvider, useTabletop } from "../contexts/TabletopContext";
import { isDmRole, type PatrolMode, type Scene, type SceneLighting, type SceneLink } from "../domain/types";
import { MapCanvas } from "../features/map/MapCanvas";
import { CreatureInspector } from "../features/tabletop/CreatureInspector";
import { DMToolbar } from "../features/tabletop/DMToolbar";
import { EncounterPanel } from "../features/tabletop/EncounterPanel";
import { campaignSetupService } from "../services/campaignSetupService";
import "./sceneNavigation.css";

export function SceneBuilderPage() { const { sceneId = "", campaignId = "" } = useParams(); return <TabletopProvider playerView={false} sceneId={sceneId} builder><SceneBuilder campaignId={campaignId}/></TabletopProvider>; }

function SceneBuilder({ campaignId }: { campaignId: string }) {
  const { state, loading, error, actions } = useTabletop(); const navigate = useNavigate();
  const [playerPicker, setPlayerPicker] = useState(false); const [selectedCharacters, setSelectedCharacters] = useState<string[]>([]);
  const [destinationSceneId, setDestinationSceneId] = useState(""); const [linkLabel, setLinkLabel] = useState("");
  const [discoverableName,setDiscoverableName]=useState("");const [discoverableHidden,setDiscoverableHidden]=useState(true);const discoverableInput=useRef<HTMLInputElement>(null);
  if (loading) return <div className="table-loading"><span>W</span><p>Opening scene builder…</p></div>;
  if (error || !state) return <div className="table-loading error"><span>!</span><p>{error ?? "Unable to load this scene"}</p></div>;
  if (!isDmRole(state.role)) return <div className="table-loading error"><span>!</span><p>DM access is required for Scene Builder.</p></div>;
  const scene = state.scene;
  const placed = new Set(state.tokens.filter(token => token.type === "PLAYER" && token.referenceId).map(token => token.referenceId!));
  const availableCharacters = state.characters.filter(character => !placed.has(character.id));
  const destinationScenes = state.scenes.filter(candidate => candidate.id !== scene.id);
  const update = (patch: Partial<Scene>) => void actions.updateScene(patch);
  const number = (key: "mapX" | "mapY" | "mapScale" | "gridSize" | "gridLineWidth" | "gridOffsetX" | "gridOffsetY" | "playerCameraX" | "playerCameraY" | "playerCameraZoom", value: string) => update({ [key]: Number(value) } as Partial<Scene>);
  const makeLive = async () => { try { await campaignSetupService.activateScene(campaignId, scene.id); await actions.reload(); } catch (reason) { alert(reason instanceof Error ? reason.message : "Unable to make scene live."); } };
  const reveal = async (revealed: boolean) => { try { await campaignSetupService.setSceneRevealed(scene.id, revealed); await actions.reload(); } catch (reason) { alert(reason instanceof Error ? reason.message : "Unable to update scene visibility."); } };
  const openPlayers = () => { setSelectedCharacters(availableCharacters.map(character => character.id)); setPlayerPicker(true); };
  const beginPlayerPlacement = () => { actions.startPlayerPlacement(selectedCharacters); setPlayerPicker(false); };
  const beginLinkPlacement = () => { if (!destinationSceneId) return; actions.startSceneLinkPlacement(destinationSceneId, linkLabel || destinationScenes.find(candidate => candidate.id === destinationSceneId)?.name || "Scene link"); };
  return <main className="scene-builder">
    <header className="scene-builder-header"><Link to={`/campaign/${campaignId}`}><ArrowLeft/>Campaign setup</Link><div><small>DM-ONLY SCENE BUILDER</small><h1>{scene.name}</h1><p>{scene.active ? scene.revealed ? "LIVE · REVEALED TO PLAYERS" : "LIVE · HIDDEN FROM PLAYERS" : "DRAFT · PLAYERS CONTINUE ON THE CURRENT LIVE SCENE"}</p></div><div className="scene-builder-actions"><button className="secondary-action" onClick={() => void makeLive()}>Make Live</button><button className="secondary-action" onClick={() => void reveal(!scene.revealed)}>{scene.revealed ? <><EyeOff/>Hide Scene</> : <><Eye/>Reveal Scene</>}</button><button className="launch-table" onClick={() => navigate(`/campaign/${campaignId}/dm`)}><Layers3/><span><small>GAMEPLAY</small>OPEN TABLE</span></button></div></header>
    <aside className="builder-sidebar">
      <section><p className="eyebrow">MAP TRANSFORM</p><NumberField label="Horizontal position" value={scene.mapX} onChange={value => number("mapX", value)}/><NumberField label="Vertical position" value={scene.mapY} onChange={value => number("mapY", value)}/><NumberField label="Map scale" value={scene.mapScale} min={.1} max={4} step={.05} onChange={value => number("mapScale", value)}/></section>
      <section><p className="eyebrow"><Grid3X3/>GRID</p><label className="builder-toggle"><input type="checkbox" checked={scene.gridType === "SQUARE"} onChange={event => update({ gridType: event.target.checked ? "SQUARE" : "GRIDLESS" })}/>Show square grid</label><div className="builder-select"><span>Grid color</span><div className="lighting-options"><button className={scene.gridColor === "#000000" ? "active" : ""} onClick={() => update({ gridColor: "#000000" })}>Black</button><button className={scene.gridColor === "#ffffff" ? "active" : ""} onClick={() => update({ gridColor: "#ffffff" })}>White</button></div></div><NumberField label="Line thickness" value={scene.gridLineWidth} min={.5} max={12} step={.5} onChange={value => number("gridLineWidth", value)}/><NumberField label="Cell size" value={scene.gridSize} min={20} max={240} onChange={value => number("gridSize", value)}/><NumberField label="Grid X offset" value={scene.gridOffsetX} onChange={value => number("gridOffsetX", value)}/><NumberField label="Grid Y offset" value={scene.gridOffsetY} onChange={value => number("gridOffsetY", value)}/></section>
      <section><p className="eyebrow"><Sun/>LIGHTING</p><div className="lighting-options">{(["BRIGHT", "DIM", "DARK"] as SceneLighting[]).map(lighting => <button key={lighting} className={scene.lighting === lighting ? "active" : ""} onClick={() => update({ lighting })}>{lighting}</button>)}</div></section>
      <section><p className="eyebrow">PLAYER START CAMERA</p><NumberField label="Center X" value={scene.playerCameraX ?? Math.round(scene.width / 2)} onChange={value => number("playerCameraX", value)}/><NumberField label="Center Y" value={scene.playerCameraY ?? Math.round(scene.height / 2)} onChange={value => number("playerCameraY", value)}/><NumberField label="Zoom" value={scene.playerCameraZoom} min={.25} max={3} step={.05} onChange={value => number("playerCameraZoom", value)}/><button className="builder-preview" onClick={actions.togglePlayerPreview}><Eye/>Player preview</button></section>
      <section className="builder-placement"><p className="eyebrow"><Users/>PLAYERS</p><button className="secondary-action compact" onClick={openPlayers}><Users/>Add Players</button><p className="builder-help">Choose the party, then click the map. They are placed in a small formation around that entrance.</p>{playerPicker && <div className="builder-picker"><div><b>Add players to this scene</b><button onClick={() => setPlayerPicker(false)}>×</button></div><button className="text-action" onClick={() => setSelectedCharacters(availableCharacters.map(character => character.id))}>Add All Players</button>{state.characters.map(character => <label key={character.id} className={placed.has(character.id) ? "already-placed" : ""}><input type="checkbox" checked={selectedCharacters.includes(character.id)} disabled={placed.has(character.id)} onChange={event => setSelectedCharacters(current => event.target.checked ? [...current, character.id] : current.filter(id => id !== character.id))}/><span>{character.name}<small>{placed.has(character.id) ? "Already on this scene" : "Ready to place"}</small></span></label>)}<button className="primary-action compact" disabled={!selectedCharacters.length} onClick={beginPlayerPlacement}>Click map to place</button></div>}</section>
      <section className="builder-placement"><p className="eyebrow"><Link2/>SCENE LINKS</p>{destinationScenes.length ? <><label className="builder-select"><span>Destination</span><select value={destinationSceneId} onChange={event => setDestinationSceneId(event.target.value)}><option value="">Choose scene…</option>{destinationScenes.map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></label><label className="builder-select"><span>Label</span><input value={linkLabel} placeholder="Cave entrance" onChange={event => setLinkLabel(event.target.value)}/></label><button className="secondary-action compact" disabled={!destinationSceneId} onClick={beginLinkPlacement}><Link2/>Place Scene Link</button></> : <p className="builder-help">Create another scene to link this map to.</p>}<div className="scene-link-list">{state.sceneLinks.map(link => <SceneLinkEditor key={link.id} link={link} scenes={destinationScenes} />)}</div></section>
      <section className="builder-placement"><p className="eyebrow"><Upload/>DISCOVERABLES</p><label className="builder-select"><span>Name</span><input value={discoverableName} placeholder="Wanted poster" onChange={event=>setDiscoverableName(event.target.value)}/></label><label className="builder-toggle"><input type="checkbox" checked={discoverableHidden} onChange={event=>setDiscoverableHidden(event.target.checked)}/>Hidden from players</label><input ref={discoverableInput} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];if(file&&discoverableName.trim())void actions.addDiscoverable(discoverableName.trim(),file,discoverableHidden);event.target.value="";}}/><button className="secondary-action compact" disabled={!discoverableName.trim()} onClick={()=>discoverableInput.current?.click()}><Upload/>Upload & place</button><p className="builder-help">After upload, click the map to place its marker. The image stays private until discovery.</p><div className="scene-link-list">{state.discoverables.map(item=><div className="scene-link-row" key={item.id}><input value={item.name} onChange={event=>void actions.patchDiscoverable(item.id,{name:event.target.value})}/><input aria-label={`${item.name} map position`} value={`${Math.round(item.x)}, ${Math.round(item.y)}`} onChange={event=>{const [x,y]=event.target.value.split(",").map(Number);if(Number.isFinite(x)&&Number.isFinite(y))void actions.patchDiscoverable(item.id,{x,y});}}/><button title={item.hidden?"Reveal to players":"Hide from players"} onClick={()=>void actions.patchDiscoverable(item.id,{hidden:!item.hidden})}>{item.hidden?<EyeOff/>:<Eye/>}</button><button aria-label={`Delete ${item.name}`} onClick={()=>void actions.deleteDiscoverable(item.id)}><Trash2/></button></div>)}</div></section>
      <PatrolPanel/><NpcInteractionEditor/>
      <section><p className="eyebrow"><Upload/>PREP</p><p className="builder-help">Use the floating tools for image layers, overlays, and creature prep. Draft changes stay off the player table until this scene is live and revealed.</p></section>
    </aside>
    <section className="builder-stage"><MapCanvas/><div className="scene-chip"><Layers3/><span><small>{scene.active ? "LIVE IMAGE SCENE" : "DRAFT IMAGE SCENE"}</small>{scene.name}</span></div><div className="map-hint">Space + drag to pan <span>•</span> Scroll to zoom <span>•</span> Drag scene links to move them</div><DMToolbar/></section><EncounterPanel/><CreatureInspector/>
  </main>;
}

function SceneLinkEditor({ link, scenes }: { link: SceneLink; scenes: Scene[] }) {
  const { actions } = useTabletop(); const [label, setLabel] = useState(link.label); const [destination, setDestination] = useState(link.destinationSceneId);
  const save = () => { if (destination) void actions.updateSceneLink(link.id, { label: label.trim() || "Scene link", destinationSceneId: destination }); };
  return <div className="scene-link-row"><input aria-label="Scene link label" value={label} onChange={event => setLabel(event.target.value)} onBlur={save}/><select aria-label="Scene link destination" value={destination} onChange={event => { setDestination(event.target.value); void actions.updateSceneLink(link.id, { destinationSceneId: event.target.value }); }}>{scenes.map(scene => <option key={scene.id} value={scene.id}>{scene.name}</option>)}</select><button aria-label="Delete scene link" onClick={() => void actions.deleteSceneLink(link.id)}><Trash2/></button></div>;
}

function PatrolPanel(){const {state,actions}=useTabletop();if(!state)return null;const token=state.tokens.find(item=>item.id===state.selectedTokenId);if(!token||(token.type!=="MONSTER"&&token.type!=="NPC"))return null;const patrol=state.patrols.find(item=>item.tokenId===token.id);const resume=()=>{if(!patrol)return;const nearest=patrol.waypoints.reduce((best,point,index)=>Math.hypot(point.x-token.x,point.y-token.y)<Math.hypot(patrol.waypoints[best].x-token.x,patrol.waypoints[best].y-token.y)?index:best,0);void actions.patchPatrol(patrol.id,{active:!patrol.active,currentWaypoint:nearest});};return <section className="builder-placement patrol-panel"><p className="eyebrow"><Route/>PATROL PATH {patrol?.active&&<small>· PATROLLING</small>}</p>{!patrol?<><p className="builder-help">Give this {token.type.toLowerCase()} a persistent route for the live scene.</p><button className="secondary-action compact" onClick={()=>void actions.createPatrol(token.id)}><Route/>Create Patrol Path</button></>:<><div className="patrol-actions"><button className="secondary-action compact" onClick={()=>actions.setPatrolEditing(state.patrolEditTokenId===token.id?null:token.id)}>{state.patrolEditTokenId===token.id?"Finish / Save":"Edit Path"}</button><button className="secondary-action compact" disabled={patrol.waypoints.length<2} onClick={resume}>{patrol.active?<Pause/>:<Play/>}{patrol.active?"Pause":"Start"}</button><button className="icon-button" title="Clear path" onClick={()=>void actions.patchPatrol(patrol.id,{waypoints:[],active:false,currentWaypoint:0})}><Trash2/></button></div><label className="builder-select"><span>Mode</span><select value={patrol.mode} onChange={event=>void actions.patchPatrol(patrol.id,{mode:event.target.value as PatrolMode})}><option value="LOOP">Loop</option><option value="PING_PONG">Ping-Pong</option><option value="ONCE">Once</option></select></label><NumberField label="Movement speed" value={patrol.speed} min={10} max={1000} onChange={value=>void actions.patchPatrol(patrol.id,{speed:Number(value)})}/><NumberField label="Pause at waypoints (ms)" value={patrol.waypointPauseMs} min={0} max={60000} step={100} onChange={value=>void actions.patchPatrol(patrol.id,{waypointPauseMs:Number(value)})}/><label className="builder-toggle"><input type="checkbox" checked={patrol.pauseDuringCombat} onChange={event=>void actions.patchPatrol(patrol.id,{pauseDuringCombat:event.target.checked})}/>Pause during combat</label><p className="builder-help">{state.patrolEditTokenId===token.id?"Click map to add waypoints. Drag circles to move; right-click a circle to remove it.":`${patrol.waypoints.length} waypoint${patrol.waypoints.length===1?"":"s"} saved.`}</p></>}</section>;}


function NpcInteractionEditor(){const {state,actions}=useTabletop();if(!state)return null;const token=state.tokens.find(item=>item.id===state.selectedTokenId);if(!token||(token.type!=="NPC"&&token.type!=="MONSTER"))return null;const interaction=state.tokenInteractions.find(item=>item.tokenId===token.id);const patch=(value:Parameters<typeof actions.updateTokenInteraction>[1])=>void actions.updateTokenInteraction(token.id,value);return <section className="builder-placement"><p className="eyebrow">NPC INTERACTION</p><label className="builder-toggle"><input type="checkbox" checked={interaction?.enabled??false} onChange={event=>patch({enabled:event.target.checked})}/>Interactable</label><label className="builder-select"><span>Type</span><select value={interaction?.type??"DIALOGUE"} onChange={event=>patch({type:event.target.value as "DIALOGUE"|"SHOP"|"BOTH"})}><option value="DIALOGUE">Dialogue</option><option value="SHOP">Shop</option><option value="BOTH">Both</option></select></label><label className="builder-select"><span>Display name</span><input defaultValue={interaction?.displayName??token.displayName} onBlur={event=>patch({displayName:event.target.value})}/></label><label className="builder-select"><span>Dialogue</span><textarea defaultValue={interaction?.dialogueText??""} onBlur={event=>patch({dialogueText:event.target.value})}/></label><p className="builder-help">Enabled NPCs are interactable on player tables. Shop purchasing remains display-only.</p></section>;}

function NumberField({ label, value, onChange, min, max, step = 1 }: { label: string; value: number; onChange(value: string): void; min?: number; max?: number; step?: number }) { return <label className="builder-field"><span>{label}</span><input type="number" value={value} min={min} max={max} step={step} onChange={event => onChange(event.target.value)}/></label>; }
