import { useEffect, useMemo, useRef, useState } from "react";
import { SceneEngine } from "./SceneEngine";
import { useTabletop } from "../../contexts/TabletopContext";
import { useAuth } from "../../contexts/AuthContext";
import { isDmRole } from "../../domain/types";
import { TokenContextMenu } from "../tabletop/TokenContextMenu";

export function MapCanvas() {
  const hostRef=useRef<HTMLDivElement>(null); const engineRef=useRef<SceneEngine|null>(null); const {state,playerView,builder,actions}=useTabletop(); const stateRef=useRef(state); useEffect(()=>{stateRef.current=state;},[state]); const {user}=useAuth(); const [menu,setMenu]=useState<{id:string;x:number;y:number}|null>(null);
  useEffect(()=>{if(!hostRef.current)return;const engine=new SceneEngine(hostRef.current,{onSelect:actions.selectToken,onMoveCommit:(id,x,y)=>void actions.commitTokenMove(id,x,y),onTokenMove:(id,x,y,final)=>actions.broadcastTokenMove(id,x,y,final),onInteract:(id)=>{if(builder)actions.previewNpcInteraction(id);else{actions.selectToken(id);void actions.interactWithNpc(id);}},onOverlayCommit:(id,x,y)=>void actions.patchOverlay(id,{x,y}),onSceneLinkCommit:(id,x,y)=>void actions.updateSceneLink(id,{x,y}),onDiscoverableCommit:(id,x,y)=>void actions.patchDiscoverable(id,{x,y}),onPatrolWaypointAdd:(x,y)=>{const current=stateRef.current;const patrol=current?.patrols.find(item=>item.tokenId===current.patrolEditTokenId);if(patrol)void actions.patchPatrol(patrol.id,{waypoints:[...patrol.waypoints,{id:crypto.randomUUID(),x,y}]});},onPatrolWaypointMove:(waypointId,x,y)=>{const current=stateRef.current;const patrol=current?.patrols.find(item=>item.tokenId===current.patrolEditTokenId);if(patrol)void actions.patchPatrol(patrol.id,{waypoints:patrol.waypoints.map(point=>point.id===waypointId?{...point,x,y}:point)});},onPatrolWaypointDelete:(waypointId)=>{const current=stateRef.current;const patrol=current?.patrols.find(item=>item.tokenId===current.patrolEditTokenId);if(patrol)void actions.patchPatrol(patrol.id,{waypoints:patrol.waypoints.filter(point=>point.id!==waypointId)});},onSceneLinkActivate:(id)=>void actions.travelSceneLink(id),onDiscover:(id)=>void actions.discover(id),onPlace:(x,y)=>void actions.placeToken(x,y),onAttackTarget:(id)=>void actions.targetAttack(id),onContext:(id,x,y)=>setMenu({id,x,y})});engineRef.current=engine;void engine.init();return()=>engine.destroy();},[actions]);
  const snapshot=useMemo(()=>{if(!state)return null;const effectivePlayerView=playerView||state.previewPlayerView;const canDm=isDmRole(state.role)&&!effectivePlayerView;return{scene:state.scene,scenes:state.scenes,sceneLinks:state.sceneLinks,discoverables:state.discoverables,overlays:state.overlays,zoneMarkers:state.zoneMarkers,tokens:state.tokens,transientTokenIds:state.transientTokenIds,motionSegments:state.motionSegments,canDm,playerView:effectivePlayerView,builder,shiftIntel:state.shiftIntel,placement:state.placement,patrolEdit:state.patrols.find(item=>item.tokenId===state.patrolEditTokenId)??null,attackSelection:state.attackSelection,attackEvent:state.attackEvent,cinematicEvent:state.cinematicEvent,selectedTokenId:state.selectedTokenId,monsterIntel:Object.fromEntries(state.monsterInstances.map(m=>[m.id,{hp:m.currentHp,maxHp:m.maxHp,ac:m.ac}])),canInteract:(token:typeof state.tokens[number])=>!canDm&&(token.type==="NPC"||token.type==="MONSTER")&&state.tokenInteractions.some(item=>item.tokenId===token.id&&item.enabled),canMove:(token:typeof state.tokens[number])=>!state.placement&&!state.attackSelection&&!token.locked&&(canDm||(token.type==="PLAYER"&&token.ownerUserId===user?.id))};},[state,playerView,builder,user?.id]);
  useEffect(()=>{if(snapshot)void engineRef.current?.render(snapshot);},[snapshot]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,textarea,select,[contenteditable=true]"))return;if(e.code==="Space"){e.preventDefault();engineRef.current?.setSpaceDown(true);}if(e.key==="Shift")actions.setShiftIntel(true);if(e.key==="Escape"){actions.cancelPlacement();actions.cancelAttack();actions.selectToken(null);}if(e.key==="Delete"&&state?.selectedTokenId&&isDmRole(state.role))void actions.deleteToken(state.selectedTokenId);};const up=(e:KeyboardEvent)=>{if(e.code==="Space")engineRef.current?.setSpaceDown(false);if(e.key==="Shift")actions.setShiftIntel(false);};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);};},[actions,state]);
  return <div className="map-canvas" ref={hostRef} onContextMenu={(e)=>e.preventDefault()}>{state?.attackSelection&&<div className="attack-target-hint"><b>{state.attackSelection.preset.replaceAll("_"," ")}</b> ready · click a target token <button onClick={actions.cancelAttack}>Cancel</button></div>}{menu&&state&&<TokenContextMenu tokenId={menu.id} x={menu.x} y={menu.y} onClose={()=>setMenu(null)}/>}</div>;
}
