import { Application, Assets, Container, FederatedPointerEvent, Graphics, Sprite, Text, TextStyle, Texture } from "pixi.js";
import type { FogRegion, FogTool, Placement, Scene, SceneOverlay, Token } from "../../domain/types";

export interface EngineSnapshot { scene: Scene; overlays: SceneOverlay[]; tokens: Token[]; fogRegions: FogRegion[]; canDm: boolean; playerView: boolean; shiftIntel: boolean; activeFogTool: FogTool | null; placement: Placement | null; selectedTokenId: string | null; monsterIntel: Record<string, { hp: number; maxHp: number; ac: number }>; canMove(token: Token): boolean; }
interface EngineCallbacks { onSelect(id: string | null): void; onMoveCommit(id: string, x: number, y: number): void; onOverlayCommit(id: string, x: number, y: number): void; onFogCommit(tool: FogTool, points: number[]): void; onPlace(x: number, y: number): void; onContext(id: string, x: number, y: number): void; }

export class SceneEngine {
  private app = new Application(); private root = new Container(); private snapshot: EngineSnapshot | null = null; private initialized = false; private destroyed = false; private renderVersion = 0; private structureKey: string | null = null; private tokenTextures = new Map<string, Promise<Texture | null>>(); private tokenDisplays = new Map<string, Container>(); private overlayDisplays = new Map<string, Container>(); private placementGhost: Container | null = null; private dragging: { kind: "TOKEN"|"OVERLAY"; id: string; dx: number; dy: number; x: number; y: number; display: Container } | null = null; private fogDraft: { tool: FogTool; sx: number; sy: number; x: number; y: number; samples: number[] } | null = null; private panning = false; private panStart = { x: 0, y: 0, rootX: 0, rootY: 0 }; private spaceDown = false;
  constructor(private host: HTMLElement, private callbacks: EngineCallbacks) {}
  async init() {
    await this.app.init({ resizeTo: this.host, antialias: true, backgroundColor: 0x151816, resolution: Math.min(window.devicePixelRatio, 2), autoDensity: true }); this.initialized=true;
    if (this.destroyed) { this.app.destroy(true,{children:true,texture:false}); return; } this.app.canvas.className = "pixi-canvas"; this.host.appendChild(this.app.canvas); this.root.sortableChildren = true; this.app.stage.addChild(this.root); this.app.stage.eventMode = "static"; this.app.stage.hitArea = this.app.screen;
    this.app.stage.on("pointerdown", (e) => this.handleStageDown(e)); this.app.stage.on("pointermove", (e) => this.handleMove(e)); this.app.stage.on("pointerup", () => this.handleUp()); this.app.stage.on("pointerupoutside", () => this.handleUp());
    this.app.canvas.addEventListener("wheel", this.handleWheel, { passive: false }); this.center(); if (this.snapshot) void this.render(this.snapshot);
  }
  setSpaceDown(value: boolean) { this.spaceDown = value; }
  center() { if (!this.snapshot || !this.app.renderer) return; const s = this.snapshot.scene; const scale = Math.min(this.host.clientWidth / s.width, this.host.clientHeight / s.height) * .96; this.root.scale.set(scale); this.root.position.set((this.host.clientWidth - s.width * scale) / 2, (this.host.clientHeight - s.height * scale) / 2); }
  async render(snapshot: EngineSnapshot) {
    this.snapshot = snapshot; if (!this.app.renderer) return; const structureKey=this.getStructureKey(snapshot); if (structureKey===this.structureKey) { this.applyPositions(snapshot); return; } this.structureKey=structureKey; const version = ++this.renderVersion; this.root.removeChildren(); this.tokenDisplays.clear(); this.overlayDisplays.clear();
    await this.renderBackground(snapshot.scene); if (version !== this.renderVersion || this.destroyed) return;
    if (snapshot.scene.gridType === "SQUARE") this.renderGrid(snapshot.scene);
    for (const overlay of snapshot.overlays.filter((o) => o.visible || snapshot.canDm)) await this.renderOverlay(overlay, snapshot.canDm);
    for (const token of snapshot.tokens.filter((t) => snapshot.canDm || t.visible)) { await this.renderToken(token, snapshot); if (version !== this.renderVersion || this.destroyed) return; }
    if (snapshot.placement) this.renderPlacementGhost(snapshot.placement, snapshot.scene.gridSize);
    if (snapshot.scene.fogEnabled) this.renderFog(snapshot); this.applyPositions(this.snapshot);
  }
  private getStructureKey(snapshot: EngineSnapshot) { const tokens=snapshot.tokens.map(token=>({...token,x:undefined,y:undefined})); const overlays=snapshot.overlays.map(overlay=>({...overlay,x:undefined,y:undefined})); return JSON.stringify({scene:snapshot.scene,tokens,overlays,fogRegions:snapshot.fogRegions,canDm:snapshot.canDm,playerView:snapshot.playerView,shiftIntel:snapshot.shiftIntel,activeFogTool:snapshot.activeFogTool,placement:snapshot.placement,selectedTokenId:snapshot.selectedTokenId,monsterIntel:snapshot.monsterIntel}); }
  private applyPositions(snapshot: EngineSnapshot | null) { if (!snapshot) return; for (const token of snapshot.tokens) this.tokenDisplays.get(token.id)?.position.set(token.x,token.y); for (const overlay of snapshot.overlays) this.overlayDisplays.get(overlay.id)?.position.set(overlay.x,overlay.y); }
  private async renderBackground(scene: Scene) {
    if (scene.mapUrl) { try { const texture = await Assets.load<Texture>(scene.mapUrl); const sprite = new Sprite(texture); const scale=Math.min(scene.width/texture.width,scene.height/texture.height); sprite.width=texture.width*scale; sprite.height=texture.height*scale; sprite.position.set((scene.width-sprite.width)/2,(scene.height-sprite.height)/2); sprite.zIndex = 0; this.root.addChild(sprite); return; } catch { /* fall through to a recognizable offline demo scene */ } }
    const floor = new Graphics().rect(0,0,scene.width,scene.height).fill(0x3d382f); floor.zIndex = 0; this.root.addChild(floor);
    const room = (x:number,y:number,w:number,h:number,color:number) => { const g = new Graphics().rect(x,y,w,h).fill(color).stroke({ color: 0x1b201d, width: 18 }); g.zIndex = 1; this.root.addChild(g); };
    room(90,90,620,330,0x5c5040); room(870,510,620,390,0x55493a); room(460,470,520,220,0x4c4438);
    const stacks = new Graphics(); for (let x=160;x<650;x+=120) stacks.rect(x,145,74,210).fill(0x2a2923); for (let x=980;x<1420;x+=130) stacks.rect(x,590,80,230).fill(0x2a2923); stacks.zIndex=2; this.root.addChild(stacks);
    const message = new Text({ text: "DEMO SCENE  ·  UPLOAD A MAP IMAGE FROM CAMPAIGN SETUP", style: new TextStyle({ fill: 0xb7a98f, fontFamily: "Arial", fontSize: 15, letterSpacing: 3 }) }); message.anchor.set(.5); message.position.set(scene.width/2,40); message.zIndex=2; this.root.addChild(message);
  }
  private renderGrid(scene: Scene) { const g = new Graphics(); const color = Number.parseInt(scene.gridColor.replace("#",""),16); for(let x=0;x<=scene.width;x+=scene.gridSize) g.moveTo(x,0).lineTo(x,scene.height); for(let y=0;y<=scene.height;y+=scene.gridSize) g.moveTo(0,y).lineTo(scene.width,y); g.stroke({ color, width: 1, alpha: scene.gridOpacity }); g.zIndex=10; g.eventMode="none"; this.root.addChild(g); }
  private async renderOverlay(overlay: SceneOverlay, canDm: boolean) {
    let display: Sprite|Container;
    if (overlay.imageUrl) { try { const texture = await Assets.load<Texture>(overlay.imageUrl); const sprite = new Sprite(texture); sprite.anchor.set(.5); sprite.width=overlay.width; sprite.height=overlay.height; display=sprite; } catch { display=this.fallbackEffect(overlay); } } else display=this.fallbackEffect(overlay);
    display.position.set(overlay.x,overlay.y); display.rotation=overlay.rotation; display.alpha=overlay.visible?overlay.opacity:(canDm?.3:0); display.zIndex=100+overlay.zIndex; display.eventMode=canDm&&!overlay.locked?"static":"none"; display.cursor="move"; display.on("pointerdown",(e: FederatedPointerEvent)=>{ e.stopPropagation(); const p=this.root.toLocal(e.global); this.dragging={kind:"OVERLAY",id:overlay.id,dx:p.x-overlay.x,dy:p.y-overlay.y,x:overlay.x,y:overlay.y,display}; }); this.overlayDisplays.set(overlay.id,display); this.root.addChild(display);
    if (canDm && overlay.locked) { const lock = new Text({ text:"◆", style:{ fill:0xd3ad76,fontSize:16 } }); lock.anchor.set(.5); lock.position.set(overlay.x,overlay.y-overlay.height/2-14); lock.zIndex=250; this.root.addChild(lock); }
  }
  private fallbackEffect(overlay: SceneOverlay) { const c=new Container(); const glow=new Graphics().ellipse(0,0,overlay.width,overlay.height).fill({color:0xc44721,alpha:.2}); c.addChild(glow); for(let i=0;i<12;i++){const flame=new Graphics().circle((i%4-1.5)*42,(Math.floor(i/4)-1)*38,16+(i%3)*5).fill({color:i%2?0xf0782d:0xc43d1e,alpha:.55}); c.addChild(flame);} return c; }
  private async loadTokenTexture(url: string) {
    let pending = this.tokenTextures.get(url);
    if (!pending) { pending = Assets.load<Texture>(url).catch(() => null); this.tokenTextures.set(url, pending); }
    return pending;
  }
  private async renderToken(token: Token, snapshot: EngineSnapshot) {
    const cell=snapshot.scene.gridSize; const radius=cell*.36*token.size; const c=new Container(); c.position.set(token.x,token.y); c.rotation=token.rotation; c.zIndex=300; c.eventMode=snapshot.canMove(token)?"static":"auto"; c.cursor=snapshot.canMove(token)?"grab":"pointer";
    const ringColor=token.type==="MONSTER"?0x718460:token.type==="NPC"?0x9b794e:0x9a86b1;
    const ring=new Graphics().circle(0,0,radius+5).fill(ringColor); if(snapshot.canDm&&!token.visible) ring.alpha=.42; c.addChild(ring);
    if(snapshot.selectedTokenId===token.id){const selected=new Graphics().circle(0,0,radius+11).stroke({color:0xe3b978,width:4});c.addChild(selected);}
    const texture=token.imageUrl?await this.loadTokenTexture(token.imageUrl):null;
    if(texture){
      const portrait=new Sprite(texture); portrait.anchor.set(.5); const diameter=radius*2; const scale=Math.max(diameter/texture.width,diameter/texture.height); portrait.scale.set(scale);
      const circleMask=new Graphics().circle(0,0,radius).fill(0xffffff); portrait.mask=circleMask; if(snapshot.canDm&&!token.visible) portrait.alpha=.42; c.addChild(portrait,circleMask);
    }else{
      const face=new Graphics().circle(0,0,radius).fill(token.type==="MONSTER"?0x394a34:token.type==="NPC"?0x6e5335:0x544965); if(snapshot.canDm&&!token.visible) face.alpha=.42; c.addChild(face); const label=new Text({text:token.displayName.slice(0,1).toUpperCase(),style:{fill:0xf4ead9,fontSize:radius*.8,fontWeight:"700",fontFamily:"Georgia"}}); label.anchor.set(.5); if(snapshot.canDm&&!token.visible) label.alpha=.42; c.addChild(label);
    }
    if(token.conditions.length){const badge=new Graphics().circle(radius*.8,radius*.8,12).fill(0x8b5039); const bt=new Text({text:String(token.conditions.length),style:{fill:0xffffff,fontSize:12,fontWeight:"700"}}); bt.anchor.set(.5); bt.position.set(radius*.8,radius*.8); c.addChild(badge,bt);}
    if(snapshot.canDm&&!token.visible){const hidden=new Text({text:"HIDDEN",style:{fill:0xe5b978,fontSize:11,fontWeight:"700",letterSpacing:1}});hidden.anchor.set(.5);hidden.position.set(0,-radius-17);c.addChild(hidden);}
    if(snapshot.canDm&&snapshot.shiftIntel){const intel=snapshot.monsterIntel[token.referenceId??""]; if(intel){const panel=new Graphics().roundRect(-70,-radius-72,140,54,7).fill({color:0x0d1110,alpha:.94}).stroke({color:0x94754f,width:1});const info=new Text({text:`${token.displayName}\n${intel.hp} / ${intel.maxHp} HP   ·   AC ${intel.ac}`,style:{fill:0xe9e5dc,fontSize:12,fontFamily:"Arial",align:"center",lineHeight:19}});info.anchor.set(.5);info.position.set(0,-radius-45);c.addChild(panel,info);}}
    c.on("pointertap",(e: FederatedPointerEvent)=>{e.stopPropagation();this.callbacks.onSelect(token.id);}); c.on("rightclick",(e: FederatedPointerEvent)=>{e.stopPropagation();this.callbacks.onContext(token.id,e.clientX,e.clientY);}); c.on("pointerdown",(e: FederatedPointerEvent)=>{if(!snapshot.canMove(token))return;e.stopPropagation();const p=this.root.toLocal(e.global);this.dragging={kind:"TOKEN",id:token.id,dx:p.x-token.x,dy:p.y-token.y,x:token.x,y:token.y,display:c};}); this.tokenDisplays.set(token.id,c); this.root.addChild(c);
  }
  private renderPlacementGhost(placement: Placement, cell: number) { const ghost=new Container();const radius=cell*.36;const circle=new Graphics().circle(0,0,radius).fill({color:placement.kind==="MONSTER"?0x718460:0x9a86b1,alpha:.45}).stroke({color:0xe3b978,width:2});const label=new Text({text:placement.name.slice(0,1).toUpperCase(),style:{fill:0xf4ead9,fontSize:radius*.8,fontWeight:"700",fontFamily:"Georgia"}});label.anchor.set(.5);ghost.addChild(circle,label);ghost.zIndex=310;ghost.eventMode="none";ghost.visible=false;this.placementGhost=ghost;this.root.addChild(ghost); }
  private renderFog(snapshot: EngineSnapshot) { const fog=new Container(); fog.zIndex=500; fog.eventMode="none"; const alpha=snapshot.playerView?.95:.42; if(snapshot.scene.fogCovered) fog.addChild(new Graphics().rect(0,0,snapshot.scene.width,snapshot.scene.height).fill({color:0x050707,alpha})); for(const region of snapshot.fogRegions){const g=new Graphics(); if(region.shape==="RECT"){const [x,y,w,h]=region.points;g.rect(x,y,w,h);}else{const [radius,...samples]=region.points;for(let i=0;i<samples.length;i+=2)g.circle(samples[i],samples[i+1],radius||80);} g.fill({color:0x050707,alpha}); if(region.mode==="REVEAL")g.blendMode="erase"; fog.addChild(g);} this.root.addChild(fog); }
  private handleStageDown(e:FederatedPointerEvent){if(this.spaceDown||e.button===1){this.panning=true;this.panStart={x:e.global.x,y:e.global.y,rootX:this.root.x,rootY:this.root.y};return;}if(this.snapshot?.placement&&this.snapshot.canDm){const p=this.root.toLocal(e.global);this.callbacks.onPlace(p.x,p.y);return;}if(this.snapshot?.canDm&&this.snapshot.activeFogTool){const p=this.root.toLocal(e.global);this.fogDraft={tool:this.snapshot.activeFogTool,sx:p.x,sy:p.y,x:p.x,y:p.y,samples:[p.x,p.y]};return;}this.callbacks.onSelect(null);}
  private handleMove(e:FederatedPointerEvent){if(this.panning){this.root.position.set(this.panStart.rootX+e.global.x-this.panStart.x,this.panStart.rootY+e.global.y-this.panStart.y);return;}if(this.snapshot?.placement&&this.placementGhost){const p=this.root.toLocal(e.global);this.placementGhost.position.set(p.x,p.y);this.placementGhost.visible=true;return;}if(this.fogDraft){const p=this.root.toLocal(e.global);this.fogDraft.x=p.x;this.fogDraft.y=p.y;if(this.fogDraft.tool.endsWith("BRUSH")){const s=this.fogDraft.samples;const lx=s[s.length-2],ly=s[s.length-1];if(Math.hypot(p.x-lx,p.y-ly)>(this.snapshot?.scene.gridSize??80)*.3)s.push(p.x,p.y);}return;}if(!this.dragging)return;const p=this.root.toLocal(e.global);const x=p.x-this.dragging.dx,y=p.y-this.dragging.dy;this.dragging.x=x;this.dragging.y=y;this.dragging.display.position.set(x,y);}
  private handleUp(){if(this.fogDraft){const d=this.fogDraft;if(d.tool.endsWith("RECT")){const x=Math.min(d.sx,d.x),y=Math.min(d.sy,d.y);this.callbacks.onFogCommit(d.tool,[x,y,Math.max(10,Math.abs(d.x-d.sx)),Math.max(10,Math.abs(d.y-d.sy))]);}else this.callbacks.onFogCommit(d.tool,[(this.snapshot?.scene.gridSize??80)*.65,...d.samples]);this.fogDraft=null;return;}if(!this.dragging){this.panning=false;return;}const drag=this.dragging;if(drag.kind==="TOKEN")this.callbacks.onMoveCommit(drag.id,drag.x,drag.y);else this.callbacks.onOverlayCommit(drag.id,drag.x,drag.y);this.dragging=null;this.panning=false;}
  private handleWheel=(e:WheelEvent)=>{e.preventDefault();const old=this.root.scale.x;const next=Math.max(.25,Math.min(3,old*(e.deltaY<0?1.1:.9)));const rect=this.app.canvas.getBoundingClientRect();const px=e.clientX-rect.left,py=e.clientY-rect.top;const wx=(px-this.root.x)/old,wy=(py-this.root.y)/old;this.root.scale.set(next);this.root.position.set(px-wx*next,py-wy*next);};
  destroy(){this.destroyed=true;this.tokenTextures.clear();this.tokenDisplays.clear();this.overlayDisplays.clear();if(!this.initialized)return;this.app.canvas.removeEventListener("wheel",this.handleWheel);this.app.destroy(true,{children:true,texture:false});}
}
